// js/sprites/bosses_r1.js — two alternate Mire bosses (face LEFT)
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  S.kettlemaw = {
    w: 48, h: 48,
    pal: { k: '#0a0d08', a: '#2a2416', b: '#4a3d22', c: '#75603a', d: '#a89468', g: '#1f3a1a', h: '#3f6b2a', w: '#31423f', e: '#ffc23a' },
    px: [
      '................................................',
      '...........................kkkkkkk..............',
      '..........................kdddddddk.............',
      '..........................kddcdcddk.............',
      '..........................kdddddddk.............',
      '..........................kdcddddck.............',
      '.....................h....kdddcdddk....h........',
      '....................kh....kddcddddk...hk........',
      '....................khh...kdddddddk..hhk........',
      '...................kghh...kdcdddcdk.hhgk........',
      '..................kgghh.kkkdddddddkhhggk........',
      '................kkcgghhkddkddcddddkkghhcck......',
      '.....................kkkkkkkkkkkkkkkkk..........',
      '.............kghhgk.kkkkkbbbbbbbbbkkkkghhk......',
      '............kgghhgkkddkbbbbbbbbbbbkkkgghhk......',
      '............kkkkkkkkkkkbbbbbcccbbbkkbbkhgk......',
      '.........kkkdddddddddkkbbdkkkkkkkkkbbbbkkk......',
      '......kkkdddddddddddddkdkkkdcccdkkkcbbbbkkk.....',
      '....kkdddddkkkkkkkkbbdkkkdddccccckkkcbbbkkkkk...',
      '..kkdddddccckeekkccbbbdkddddccccckkckcbbbkkdd...',
      '.kddddcccccckkkkcccbbbbkddddccccckccckcbbbkkk...',
      'kkkdcccccccccccccccbbbbkkdddccccckcccckcbbkkk...',
      'kkccccccccccccccccckbbbkkdddcccckkccccdkcbkghhk.',
      'kcccccccccccccccccckbbbkkdddcccckkccccckcbkghhg.',
      'kkkccccccccccccccccbkbbkkddkkkkkkccccccckkkkghk.',
      'akdkkkcccccccccccccbkbbkkkkkccckkkcccccckkbbkk..',
      'aaddkkkkkkcccccccccbbbbkkkddcccckkkcccckkkbbbkk.',
      'aaadaakkkkkkkkccccccbbbbkkddccckcckkcckkbkbdckk.',
      'aaddaaaaaakkkkkkkkkkkkkkkkkdccckccdkcckbbbkbbkk.',
      'kkddkkkkkkkkkkkkkccccbbbbkkcccckcccckkbbbbkbbbkk',
      'kkkkkkkkkkkkkccccccccbbbbkkccccccccckbbbbbkbaakk',
      'kaaccccccccccccccccccbbbbkccccccccckbkbbbbbbaakk',
      'kaaaaaccccccccccccccccbbbbkccccccckbbkbbbdckaakk',
      '.kkakkaaaacccckkccccccbbbbkccdccccbbbbbbbbkbbkkk',
      '...kkkkaaaaaaaakkccccbbbbbbbbccccbbbbbbbbkabbckk',
      '......kkkkaaaaaaaaaakbbbbbbbbkkkkkbbbbbbkkaabckk',
      '..........kkkkkaaaaakabbbbbbbck..kabbbbbckkabck.',
      '...............kkkkkkabbbbbbbck..kabbbbbck.kabk.',
      '....................kaabbbbbbck.kaabbbbbbck.kak.',
      '...................kaabbbbbbbck.kaabbbbbbck.....',
      '...................kaaabbbbbbbckkaaabbbbbck.....',
      '..................kaaabbbbbbbbckaaabbbbbbck.....',
      '..................kaaabbbbbbbbckaaabbbbbbck.....',
      '.................kaaaabbbbbbbbkaaaabbbbbbck.....',
      '................kddkddkddkddkdkddkddkddkddck....',
      'wwwkwwwwwwwwwwwkkkdkkdkkdkkdkkkkdkkdkkdkkdk...ww',
      'wwwwwwkwwwwwwwwwwwwwwwkwwwwwwwwwwkwwwwwwwwwwwwww',
      'kkwwkwwwwkwwkwwwwwkwwwwkkwwwkwwwwwkwwkwwwwwkwwkk',
    ],
  };

  S.sunken_choir = {
    w: 48, h: 48,
    pal: { k: '#050a0e', a: '#132a33', b: '#1d4a45', c: '#728c80', d: '#adc4a8', f: '#e4efdc', g: '#2c4a24', h: '#5d8c39', e: '#72ffd4' },
    px: [
      '................................................',
      '................................................',
      '................................................',
      '..................kkkkkkkk......................',
      '................kffcccccahgk....................',
      '..............fffdcccckccgaak...................',
      '.............kkkkkckkkkccggak...................',
      '.............keekkckeekkcahak...................',
      '............kkeekkckkkkccaaak...................',
      '............kkkkkccccccccaaak...................',
      '............kddccccccccccaaak...................',
      '...........kddkcccccccccaaahg...................',
      '...........kkckccccccccaaakg.........hg.........',
      '...........hgckcccccccaaak.gghg......g..........',
      '...........gkkkkkkkkkkkkk...hg...kkkkggk........',
      '...........ggeeeeeeeeak.kccggggkkdcccchakk......',
      '...........kheeeeeeeak..kcgak.hdkkkkcggaaak.....',
      '...........ggkkkkkkkkkkkkkchgggkeeekkccaaak.....',
      '...........kddcccccccaaak...g.kdkkkkcccaaak.....',
      '...........kddccccccaaak...gghgkdkkkkccaaak.....',
      '............kkdccccaaak....h..g.kkeekcaaak..hg..',
      '..............kkdcaaakkkkkkggggk.kkkkaaak...g...',
      '..............kkkkkkkkkkkkkkghkkkkkdkkkk....gg..',
      '............kkkkkckkafkadkhgkggkaakkdkk......h..',
      '..........kkkckkkkfkafkadkagkadkaaakkkkk....gg..',
      '........kkkckkafkafkafkadkaggadkaaakkdkk...g....',
      '......kkkckkdaafkafkafkadkadhadkaaaakkdkk...hg..',
      '.....kkckk.kdaadkadkadkadkadkadkaaaak.kkkk...g..',
      '.kfkkdck...kdaaadkadkadkadkadkadkaaak.kdkk..gg..',
      'kfkfkfk....kddaadkadkadkadkadkadkaaak..kkkk.h...',
      'kfddddk.....kdaackackackackackackaaak..kkkk.gg..',
      '.kdddk..kkkkkkkaackackackackackacaak...kkkk.....',
      '..kkk.kkdccccaakkckackackackackaaaak...kdkk.....',
      '.....kdkkkckkkaakkkkkkkkkkkkkkkcaaak....kkkk....',
      '.....kdkekckekaakccccccccccccccccaaak...kdck....',
      '......kdkeeekaaakccccccccccccccccaaak...........',
      'baaaaaakkkkkkkkkccccccccccccccccccaaakaaaaaaabaa',
      'aaabaaaaaaakddccccccccccccccccccccccaakkaaaaaaaa',
      'aaaaaabaekkdccccccccccccccccccccccccccaakkkaaaaa',
      'bkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdkdk',
      'aabbbbbbaaaabaaaaaaakdkdkaaaaabaaaaaaaabaaakdddk',
      'aaaaaabaaaaaaaabaaakkdddkkkkkkaaabaaeaaaaabakdka',
      'bakdkdkaabaaaaaaaababkdkbbbbaaaaaaaabaaaaaaaabaa',
      'aakdddkaaaaabaaaaaaaabaaaaaaaaeaaaaaaaabakkkkkka',
      'aaakdkbakkkkkkkkaaaaaaaabaaaaaaaabaaaaaaaabbbaaa',
      'baaaaaaaabbbbbaaaabaaaaaaakkkkkkkkkkkkaaaaaaabea',
      'aaabaaaaaaaabaaaaaaaabaaaaabbbbbbbbbaaabaaaaaaaa',
      'aaaaaabaaaaakkkkkkkkkaaabaaaaaaaabakkkkkkkkaaaaa',
    ],
  };

})();
