// js/sprites/bosses_r2.js — the two alternate High Canopy bosses (face LEFT)
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  // The Skywrack — storm-borne harpy eagle: spread wings, hooked gold beak, barred chest.
  S.skywrack = {
    w: 48, h: 48,
    pal: { k: '#0a1016', a: '#1c2f3f', b: '#31556f', c: '#5a87a4', d: '#94bbcf', w: '#e8f4fa', y: '#e8b53c', o: '#9a6c16', e: '#7fe8ff' },
    px: [
      '.......e..................e..................ee.',
      '....kkeke.................e......e.............e',
      '...kkbakk................e.......e.........kkk..',
      '...kbbkakk.................e....e.........kkbkk.',
      '..kkabbkakk...............e.......e......kkbkdk.',
      '.kkaaabbbakk..............e......e......kkbkdbk.',
      'kkaaaaabbbakk..........................kkbbdbbk.',
      'kaaaaaaabbbakk........................kkbbdbbbkk',
      'kaaaaaaaabbbak.....kkk...............kkbbdbbbbbk',
      'kaaaaaaaaabbbkk....kbkk.............kkbbdbbbbbbk',
      'kaaaaaaaaaabkkkk..kkbbk.............kbbdbbbbbbbk',
      'kaaaaaaaaaaakbkkk.kbbbk............kkbddbbbbbbkk',
      'eaaaaaaaaaaakbbkkkkbbbk...........kkbddbbbbbakk.',
      'keaaaaaaaaaakbbkbkkbbbk..kkkk....kkbbdbbbbbaakk.',
      'eaaaaaaaaaakkbbkkkbbbbk.kkbbk....kbbddbbbbbabk..',
      'kaaaaaaaaaakbbbbkkbbbkkkkbbbk...kkbddbbbbbaakke.',
      'kaaaaaaaaaakkkkkkkkbbkkkbbbbk..kkbbdbbbbbaabk..e',
      'kaaaaaaaakkkcddccckkbkkbbbbkk..kbbddbbbbbaakke..',
      'kaaaaaaakkkkkkddddckkkkkkbbk..kkbddbbbbbaaak....',
      'kaaaakkkkkyyykaadddckkkckkkkkkkbddbbbbbaaakk....',
      'kaaakkyyyyywwwwadddcckccckkdkkbbdbbbbbbaaak.....',
      'kaakkyyyyyoooewaddccccccckbbdkkddbbbbbaaakk.....',
      'kakkyyyoookwkkwaacccccccckkbbbkkbbbbbaaakk......',
      'kkkyyoookkowwwwaaccccccccckbbbbkkbbbaaaak.......',
      '.kyyyykooooookaaaccccccccckbbbbbkkbbaaakk.......',
      '.kkyyyyooooookcccaaaaacccckkbbbbbkbaaakk........',
      '..kyyyyooooookaaaaaaaaccccckbbbbbkaaaak.........',
      '..kkyykkkkkkkkaaaaaaaccccckkbbbbbkaaakk.........',
      '...kkkkaaakaaaaaaaaaaccckkkbbbbbbkkakk..........',
      '...kaakaaakkkkkkkkccckkkkbbbbbbbbbkkk...........',
      '...kkakkaaakaaakdkckkkwbbbbbbbbbbbkk............',
      '....kaakaaakaaakdkkkwwwdddbbbbbbbbkk............',
      '....kkakaaaakaakdwwwwwwddddbbbbbbbk.............',
      '.....kaakaaakaakbwwwwwwbbbbbbbbbbbk.............',
      '.....kkakaakkkkkdwwwwwwbbbbbbbbbbbk.............',
      '......kkkkkk...kkdwwwwdddddbbbbbbkkkk...........',
      '................kddwwddddddbbbbbkkcckk..........',
      '................kkbbbbbbbbbbbbbkkaacckk.........',
      '.................kkbbbbbbbbbbbkkaaaacckk........',
      '.................kkkddddddddbkkbbbaaacckkk......',
      '.................kkkkkkkkkkkkkkbbbbaaaccakk.....',
      '.................kyykck..kkyykkabbbbbaaccakk....',
      '................kkyykkk..kkyykkaaabbbbbaccak....',
      '...............kkyyyykk.kkyyyykkaaaabbbbacckk...',
      '..............kkyyyykykkkyyyykykkaaaabbbbbbck...',
      '..............kyykykkkykyykykkkykaaaaaabbbbkk...',
      '..............kkkkyk.kkkkkkykkkkkbbaaaaabbbbk...',
      '.................kkk......kkk.kkkkkkkaaaakkkk...',
    ],
  };

  // The Last Watchman — a dead sentinel in a hood, jade mask, the seal of his office.
  S.last_watchman = {
    w: 48, h: 48,
    pal: { k: '#0b1114', a: '#232e31', b: '#3b4a4d', c: '#5f7275', d: '#93a8aa', w: '#dcecec', g: '#134a3d', h: '#2f9070', e: '#7ff0c4', y: '#c49a3a' },
    px: [
      '..kbkk...........kkkk......................kkbk.',
      '..kbbk........kkkkbbkkkk...................kbbk.',
      '..kkbk......kkkbbbbkbbbkkkk................kbkk.',
      '...kbkk....kkbbbbbbyyabbbbkk..............kkbk..',
      '...kbbk...kkbbcbbbbyybaabbbkk.............kbkk..',
      '...kkbkk.kkbbcbbbbbbbbaaabbbkk...........kkbk...',
      '....kbbkkkbkkkkkkkkkbbaaaaabbk...........kbbk...',
      '....kkbkkbkkhhhhhkkkkkbaaaaabkk.........kkbkk...',
      '.....kbkbkkhhhhhhhhhhkkaaaaaabk......w..kbbk....',
      '.....kbkckhhhhhhhhhghhkaaaaaabkk........kbkk....',
      '.....kkkkkhhhhhhhggggggkaaaaaabkk......kkbk.....',
      '......kkkhgggggggggggggkaaaaaaabk......kbkk.....',
      '......kkhhgggggggggggggkkaaaaaabk.....kdbk......',
      '..w..kkhhgghhhkkkkhgggggkaaaaaaak.....kbkk......',
      '....kkhhggkkkkeeekhgggggkaaaaaaak....kkbk.......',
      '...kkhggghkeeeegekhgggggkaaaaaaak....kbbk.....w.',
      '...khgghhhkeeeeegkhgggggkaaaaaaak...kkbkk.......',
      '...wkkhhhhkkkkkkkkhgggggkaaaaaaakk..kbbk........',
      '....kkkhhhhhhhhhhhggggggkaaaaaaabk..kbkk........',
      '.....kkkhhhhhhhhhhgggggkkaaaaaaaak.kkbk.........',
      '.....kkkkkhhhhhhhhgggggkbaaaaaaaak.kbkk.....w...',
      '.....kkckkkhhhhhkkkekggkbaaaaaaaakkkbk..........',
      '......kkckkhkekkekkkkggkbbaaaaaaakkkkk..........',
      '.......kkkkhkkkkkhggggkkbbaaaaaaakcckk..........',
      '.......kkckkkhhhhhgggkkbbbaaaaabkkccckk.........',
      '.......kkkcckkkkhhgkkkbbbbaabkkkkccccckk........',
      '......kkkkkccckkkkkkbbbbbbkkkkkcccccccck........',
      'd.....kkbbkkckkbkkkkkkkkkkkabbkkccccccckk.......',
      '.....kkkbbbyykbbbbkkkkkkkkaaayykkkcccccckk.....d',
      '....kkkbbbbbyyybbbbkaacaaaayyybbbkkkccccck......',
      '....kckbbbbbbbyybbbkaacaayyycabbbbkkkcccckk.....',
      '..wkkkkbbbbacbbbyykkaacyyyaacabbbbbkkkkccckk....',
      '...kckbbbbbacabbbyyyayyyaaaaccabbbbkkakkkkck....',
      '...kkkbbkkkkcaabbbkyyyyaaaaaacabbbbbkaaakkkk....',
      '.....kbkkddccaabbkkyggyaaaaaacaabbbbkaaakk......',
      '.....kkkdddckkbbbkaygeyaaaaaacaabbbbkkaaak......',
      '....kkdddddcdkbbbkayyyyaaaaaacaabbbbbkaaak...w..',
      '...kkddddddckkbbkkaaacaaaaaaaccabbbbbkaaak......',
      '...kdddddddckbbkkaaaacaaaaaaaacaabbbbkaaakkk....',
      '..kkddddddcckkkkbaaaacaaaaaaaacaabbbbkkaaakkkk..',
      '.kkdkkddddckkbbbbbaaacbaaaaaaacaabbbbbkaaakddkk.',
      'kkddkkkdkkckbbbkkbbabcbbaaabbaaaabbbbbkkkkkdddk.',
      'kdkkkkddkkckbbkkkkbbbkkbaabbbaaabkkbbbkkddddddk.',
      'kkkkkddkkkdkkkkddkbbkkkbbbbkkbabbkkbbkkwwddddkk.',
      '...kddkkkddkwwwwwkkkkwkkbbbkkkbbkkkbbkwwwwwkkk..',
      '...kdkkwkdkkwwwwwwwwwwwkbbkkwkbbkwkkkkwwwwwk....',
      '...kkkkwkdkwwwwwwwwwwwwkkkkwwkkkkwwwwwwwwkkk....',
      '......kkkkkwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkk......',
    ],
  };

})();
