// js/sprites/bosses_r0.js — two alternate Undergrowth bosses (face LEFT)
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  S.thousand_mouth = {
    w: 48, h: 48,
    pal: { k: '#0c0705', a: '#3b160f', b: '#68281a', c: '#9c4523', d: '#d17836', e: '#ff5f22', v: '#968c74', w: '#e8e2cd', g: '#8cff4a' },
    px: [
      '.............................kvvk....kkkk.......',
      '............................kvwk...kkvvvvkk.....',
      '...........................kvwk..kkvvwwkvvvkk...',
      '..........................kvwk.kkvvwwkk.kkvvvk..',
      '.........................kvwkwkvvwwkk.....kkvvk.',
      '........................kwwwwwvwwwk.........kk..',
      '.......................kwwcwwwkwwwwk............',
      '.....................kkwwwwawkkkwwvvkkkkkk......',
      '...................kkgkkwwwwkkgkkwvvcvvvvvk.....',
      '.................k.kgggkwwwwwkkkwwvvvkkkkk......',
      '..........k....kkwkggeggkwwwwwkwwcvvvk..........',
      '........kkwkkkkwwwwkgggkwwwwwwwwvvavvvk.........',
      '.......kwwwkwwwwwwwkkgkkcwvvwvvvvvvvvk..........',
      '.......kwkkkkkwwwwwwwkwwwwwvvvvvvvvcvk..........',
      '......kwwwwkwwwwwwwcawwwwwwvcvvvvvvvvk..........',
      '.......kwwwwwcawcawwwwwwwwwvvvcvvvvvk...........',
      '.......kwwwvwvkvkvkvkvkvwwwwvvvavvvk............',
      '.......kcakkkkkkkkkkkkkkkkwwwvvvvvk..kk.........',
      '........kkkwwwwwwwwwwwwwwvbaawkkkk..kcak...kk...',
      '...........kvwvcvwvwvwawwvbaaak.kkk..kk...kcak..',
      '......kk...kvvvvvvvvvcvvvvvbbakkaaak.......kk...',
      '.....kcakkkkdvvvvvvvvvvvvvvbaaaababakk..........',
      '......kkkddbccdbbabaawwwvvvvvvabaaabaak.......kk',
      '......kdbcbcbabcbawwwvvvvvvvvvvvvaaaaaakk....kca',
      '......kdcccbbabawwvvvbbbvaebabvvvvvaaabbbk....kk',
      '......kdbdcccaawvvbabwwwvvvvvvbbkkvvaaaabakk....',
      '..kk.kdccbcaaackkkwwwvvvvvvvvvvvk.kvaaaabaaak...',
      '.kcakddcbccakkk..kvvvbabvcbbbbvvvk.kkbbabaaaak..',
      '..kkkdbbcdkk.....kcbwwwwvvvvvbcacvk..kbababbak..',
      '...kdbcdbbk.....kwwwvvvvvvvvvvvvaaakk.kkbaabak..',
      '...kdcccck.....kwvvvbceavabbbvvvvvvaak..kbaaak..',
      'kkkdccccak....kvvbbbwwwwvvvvvacbvvvvaak..kbaaak.',
      'dcccbccak.....kacwwwvvvvvvvvvvvvbaavaaak.kbbaak.',
      'kdcbccak......kwwvvvbbccvbbbbvvvvvaaaaak..kabaak',
      '.kdcceak......kvvbacbwwwvvvvbcabvvvaaabk..kaabak',
      'kdcdccabk.....kaabawwvvvvvvvvvbcaavaabbk..kaabba',
      'kdcccabk.....kabcwwvvbbbvbcbvvvvbabaabak..kaaabb',
      'dcdcccak....kcacwvvbbbbbbcbabavvvbaaabak.kaaabbb',
      'kkecckk...kkabbbvcabebcbbbbbcbabvcbaabak..kaaaaa',
      '.kdkk...kkabbbacbbabbbbcbbbbaabcbabaabaak.kaeaab',
      'kdck...kdabcabaabbbabbbbbbaabbbccabaaababk.kkbkk',
      'kdk...kcabbbbabcabbacbbccbccbcaaaaeaaabbak...k..',
      '.k...kdcaccccbcbbbbbabcbbbbbcbbcababbababakk....',
      '....kdccaccbaabbbaababbbabccccbbbaaaaaaaabaak..k',
      'kk..kdcccebdcabbcbbbabbbcabbacbbaaaabaabbabaakkc',
      'cakkdcccbcacbbbabecbabbababbbcccaaaaaabaaaabaakk',
      'kk..kdccbcacbbbbcbbabbbbabbbcbbacbabaaaaaaaabk..',
      '....kdcbbdcbbbbccbbbbccbabbcbabbbbaaabaaaabaak..',
    ],
  };

  S.old_gullet = {
    w: 48, h: 48,
    pal: { k: '#08120a', a: '#1c3a1b', b: '#2f5f28', c: '#4c8a36', d: '#7db84a', y: '#c2b451', g: '#dcf35c', w: '#e5a5ae', e: '#f0a828' },
    px: [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '..............k.................................',
      '...........kkkdkkk..............................',
      '..........kdddkdddk.............................',
      '.........kdkkkekkkdk..............k.............',
      '........kdkkgeyeekkdk........kkkkkdkkkkk........',
      '........kckgyyyyyekck......kkdddddcdddddkk......',
      '........kckyyyyyyykck...k.kddcccccccccccddk.....',
      '.......kdkkkkkkkkkkkdkkkdkdccdccccadccccccdk....',
      '........kbkeeekeeekacdddcddccccaaacgcaaacccdk...',
      '........kbkeeeeeeekaccccccccacaaaaacaaaaaaccdk..',
      '.......kbbkkeeeeekkaaccaaccaaaaaaaaaaaaaadaccdk.',
      '.....kkdbbbkkkekkkaaaaacaaaaaaaaaaaaaaaacccaccdk',
      'k..kkddcbbbaaakaaaaaaccaccaaaaadaaaaaaaaacaaacck',
      'wkkddcccbbaaaaaaaaaaacaaacaaaacccdaaaaaaaaaaaacd',
      'wweccccbbbbaaaaaaaaacaaaaackkaaccccaaadaaaaaaaac',
      'wwwccbbbbbbaaaaaaaaaacaakkkkkaaaacaaacgcaaaaadac',
      'wwwbbbbbbbbbaaaaaaaaakkkkkkkkkkaaaaaaacaaaaaccca',
      'wwwwbbbbbbbbaaaaakkkkkkkaaaaakkaaaaaaaaaaaaaacaa',
      'dwwwwbbbbaaaakkkkkkkkaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'kbwwwwaaakkkkkkkkaaadaaaaaadaaaaadaaaaaaaaaadaaa',
      'kcawwwwkkkkkkwaaabbcccbbbbcccbbbcgcabbaaaaacccaa',
      'kkkkwwwkkwwwwyyyyyybcabbcbbcabbbbcabbbbbaaaacaab',
      'kkkwwwwwwyyyyyyyydyyybbbbbbbbcbbbbbbbbbbbbbabbbb',
      '..kbbyyyyyyyygyycccyyycydcccccccccccccccbbbbbbbb',
      '...kkyyyyggggggggcacyyycccyyyydccccccccdccccbbbb',
      '.....kygggggggggggggyyyycayyycgcyyccccccccccccbb',
      '....kyygggggggggggggyyyyyyyyyycayyycccccacccdccb',
      '.....kgggggbgggggggggyyyyyyyyyyyyyyyyccccccccccc',
      '....kcbbbbbbbbbbggggyyyyyyyyyyyyyyyydyyyyyyycacb',
      '....kbcccbbbbbbbbbggyyyyyyyyyyyyyyycccyyybyyyybk',
      '...kabbbaccbabbbbbyyyyyyyyyyyyyyyyyycbabbbabbbak',
      '..kkabbbabbbabbbbbbyyyyyyyyyyyyyyyyybbabbbabbbak',
      '.kaaaaaaaaaaaaabbbyyyyyyyyyyyyyyyyybbbabbbabbbab',
      'kaaaaaaaaaaaaaaabbbbbbbybbbbbbbbbbbbbbabbbabbbak',
      '.kakaaakaaakaaabbbbbbbbbbbbbbbbbbbbbbbabbbabbbak',
    ],
  };

})();
