// js/sprites/monsters_e.js — Tier 5 monsters + region bosses + Heart of the Jungle (face LEFT)
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  S.ancient_golem = {
    w: 32, h: 32,
    pal: { k: '#141a20', a: '#3a4350', b: '#646e7e', c: '#98a3b2', r: '#5ef2d6', v: '#2d6b2a', w: '#5fae4c' },
    px: [
      '................................',
      '................................',
      '.........kk.....................',
      '......kkkwwkkkkk................',
      '......kbbwbbaabk................',
      '.....kaaaaaaaaak................',
      '.....kaaaaaaaaak........kkkk....',
      '.....kkkrkbrkbbk.......kvbbbkk..',
      '...kkbkkkkbkkbbkkkkkkkkvvbbbbbk.',
      '...kbbkkkkkbbbbkbbbbbkwvbbbbbbkk',
      '..kbbbkbcbbbabbkabbbbkwwababbbbk',
      '..kbkkkkkkkkkkkkbbabakvbcbbabbkk',
      '..kkbbbkbbbbabbrbrbbvvkrbabbabk.',
      '..kbabcbkbbkaaabrbbbvbbkkbbbkkk.',
      '..kbbavbkbkkbabrbwwvabbbbkkkbbbk',
      '..kbbbbvwwbbbacbbvwcabbbbbbkbabk',
      '.kbbbbbvvbbbbbacvcbraabbbbbabbbk',
      '.kbbbbbkvbrrbbabvbbrbaabbabbbbbk',
      '.kbaabbkvbrabbbvcbbrbabbbabbbbbk',
      '.kbbbbbvbbrrbbbvcbbcbbabbbbbkbbb',
      'kbbbbabvbaaabwvvbbbbbbaabbbbkbba',
      'kbbbbbkbbbbbbwwabbbbbbbbbbbbkbab',
      'kbkkkbkcbbcbbbvvbbbbcbbbabbbkkkb',
      'kkbbbkkkkkkkkkkvkkkkkkkkkkkkbbbk',
      'kbbabbkkkbbabbbbvkkbbbbbbbkababb',
      'cabbbabkkbbabaack.kbcbbabbkbbbbb',
      'cbbbbbbkkbabrbbbk.kbbbrbbbkbbbbb',
      'cbbbbbbkkkkkakkkkkkkkkkkkkkkbbbk',
      'kbbcbbkkaaaaaaaaakaaaaaaaaakbkk.',
      'kkbbckkkaaaaaaaaakaaaaaaaaakk...',
      '..kkk..kaaaaaaaaakaaaaaaaaak....',
      '.......kkkkkkkkkkkkkkkkkkkkk....',
    ],
  };

  S.jade_serpent = {
    w: 32, h: 32,
    pal: { k: '#0b2a1a', a: '#176b3c', b: '#2bb36c', c: '#8ff2b4', g: '#e9c64c', h: '#8a6a14', e: '#ff4a2a' },
    px: [
      '................................',
      '.......k........................',
      '......kgk.......................',
      '....k.kgk.k.....................',
      '...kgkkgkkgk....................',
      '...kghggghgk....................',
      '...kcbbbbbck....................',
      '..kceebbbbbck...................',
      'k.kckkbbbbbbk...................',
      'ekcbbbbbbbbbkk.k................',
      'ekkkkbbbbbbbcgkgk...k...........',
      'k...kcaabbbbgbhhgk.kgk..........',
      '.....kkkcbbbghbgkkkghgk.........',
      '........kcbghbbbccccgkk..k......',
      '.........kgahbbbbbbbccckkgk.....',
      '..........khcbbbbbbbbbbcghgk....',
      '...........kkcaaabbbbbbbbgk.....',
      '.....kk......kkkkcaaabbbbbk.....',
      '....kcck.........kkkkcbbbbckk...',
      '...kcbak.............kcabbbcgk..',
      '..kcbak...............kkcbbghgk.',
      '.kcbbkk.................kcbbgk..',
      '..kcbkgk................kcbbbk..',
      '..kcbghgk..k......k....kcbbbak..',
      '..kcbbgk..kgk....kgk..kcbgbak...',
      '...kcbckkkghgk..kghgkkkcghgk....',
      '...kcbbccccgkkkkkcgccccbbgk.....',
      '....kcaabbbccccccbbbbbbbbak.....',
      '.....kkkcaabbbbbbbbbaaaaak......',
      '........kkkcaaaaaaaakkkkk.......',
      '...........kkkkkkkkk............',
      '................................',
    ],
  };

  S.void_panther = {
    w: 32, h: 32,
    pal: { k: '#35245a', a: '#0b0716', b: '#1b1233', s: '#ffffff', t: '#a48eff', e: '#c94dff' },
    px: [
      '................................',
      '................................',
      '................................',
      '...........................kk...',
      '..........................kbbk..',
      '..........................kbabk.',
      '...........................kbabk',
      '...k......k.................kbab',
      '..kbk....kbk................kbak',
      '..kbbkk.kbak...............ksbak',
      '...kbbbkkbak................kbak',
      '...kbaabbaabk...............kbak',
      '..kkbaaaaaaak....k.........kbatk',
      '.kbbaaaaaaakkkkkkbkkkkkk...kbak.',
      '.keeeaaeeaabbbbbtabbbbbbkkkbaak.',
      '.kbaaaaaaaaaaaaaaaaasaaabbbaak..',
      '.kaaaaaaaaaaaasaaaaaaaaaaataak..',
      '.kkkaaaaaaaaaaaaaaaaaaaaaaaak...',
      '..kbaaaaaasaaaaaaaataaaasaaabk..',
      '...kkkkbaaaataaaaaaaaaaaaaaaak..',
      '.......kbaaaaaaaasaaaataaaaaak..',
      '......kbaaaaaaaaaaaaaaaaaasak...',
      '......kbaaaaaaaaaaaaaaaaaaaak...',
      '.....kbaaaaaaakkkbkkbaaaaaak....',
      '.....kbaaakbatk..k.kbaaaaaabk...',
      '....kbasaabaaak....kbaakbaaabk..',
      '....kbaaakbaaak....kbaakkbaaak..',
      '...kbtaaakbaak.....kbaakkbaaabk.',
      '..kbaaaakkbaak.....kbaak.kbaaak.',
      '.kbaaaak.kbaak.....kbaak..kbaabk',
      '.kbaaak.kbaaabk...kbaaabk..kbaak',
      '.kbaak...kkbkk.....kkbkk...kbaak',
    ],
  };

  S.titan_beetle = {
    w: 32, h: 32,
    pal: { k: '#2a1608', a: '#5a3814', b: '#9a6820', c: '#d3a13c', d: '#f5d97f', e: '#ff5a1a' },
    px: [
      '................................',
      '.................k..............',
      '................kck.....k.......',
      '...........k....kcck...kck......',
      '..........kck..kcbbk...kck......',
      '..k.......kcck.kcbbk..kcbck.....',
      '.kck......kcbk.kcbbckkcbbbk...k.',
      '.kck.....kcbbckcbbbbckcbbbk..kck',
      '.kcck....kcbbbkcbbbbbkcbbbk.kcbk',
      '.kcbk....kcabbcbbbbbbcbbbbckcbbk',
      '.kcbk....kcabbbbbcbbbbbbbbbkcbbk',
      '.kcbk....kcaccdddddccccbbbbcbbbk',
      '..kcck..kcbadddddddddcccbbbbbabk',
      '..kcbk.kcbcaccdddddccccccbbbbbbk',
      '..kcbckcbabaccccccccccccbbbbbbak',
      '..kcbbkcbbaacccccccccccbbbbbbbk.',
      '...kcbkcbbbabbbbbcbbbbbbabbbbbk.',
      '...kcbcbbbbaaaaaaaaaaaaaaaaaaack',
      '..kcbbbbabaabbabbbaabbbbbbbbbbk.',
      '.kceebbbbbbababbbbbbbbbbbbbbbbk.',
      '.kckkbbbabbabbbbbbababbbbbbbbak.',
      '.kcbbbbbbbbabbbbbbbbbbbbbbbbak..',
      'kcbaabbbabbabbbbbbbbbbbbbbbak...',
      'cbakkcaakcbabbbbabbbbbbbbbak....',
      'cak..kkkcbbaabbbbbbbbbbbbbk.....',
      'ck....kcbaaakcbbbbbaabbbaak.....',
      'k....kcbbkaakkcbaabkkcbbaaak....',
      '....kcbbaaak.kcbaaak.kcbbaak....',
      '....kcbakaakkcbbkaak.kcbbbaak...',
      '..kkcbakaak.kcbakaak..kcbbbaak..',
      '.kaaaakkaakkcbbkkaak...kcbbaak..',
      '..kkckkaaakaaaakkaaak..kaaaaaak.',
    ],
  };

  S.plague_shaman = {
    w: 32, h: 32,
    pal: { k: '#141a10', w: '#ece5cc', x: '#b3a988', a: '#2a2a18', b: '#474828', c: '#666a38', g: '#4aa63a', h: '#93e56c', e: '#7dff5a' },
    px: [
      '..........................kkk...',
      '.........................kwwwk..',
      '............k..k..k......kwwwk..',
      '...........kxkkxkkxk....kxkwkxk.',
      '............kxkkkxk......kwwwk..',
      '.........kkkkaaaaakk.....kxkxk..',
      '.......kkwwwaaaaaaaak.....kxk...',
      '......kwwwwwwwaaaaaakk....kxk...',
      '.....kkwweewwwaaaaaaak....kxk...',
      '...kkwwwwkkwwwwaaaaaak....kxk...',
      '.kkwwxxwwwwwwwaaaaaaak....kxk...',
      'kwwxxxxxxwwwwwaaaaaakk....kxk...',
      'xxxxkkkkkxwwaaaaaaaakk....kxk...',
      'kkkk.....kkkkaaaaakkakkk..kxk...',
      '........kkabakkkkkkbbbbbkkkxk...',
      '......kkbbbbbbbkbkbbabbbbbkk....',
      '....kkbabbbbbakbbbkabbbabwwwk...',
      '...kkaababbbbkkabakkbbbbbwwwk...',
      '..kwwwbbbbbkkbabbbbbkkbaawwwk...',
      '.kxwwwbbbkkbbbbbbbabbbkkkbkk....',
      '..kxkwbkkbbbbbbaabbbbbbk.kkxk..h',
      '...kkhkkkbababbbbbbbabbak.kxkkkk',
      '.hkhhghhkabbabbbbbbaaabbk.kxkhhh',
      '.khgggggbabbbbbabbbbbbbbk.kxhggg',
      '.khgggggbbbbbbbbbbbahbbbbkkxhggg',
      'khgggghggbbbabhbbbbbbbbabkkxhggg',
      '.khgggggggabbbbbbbbbbbbbbkkxkhgg',
      '.khggggggbbbbbabbbbbbbbbbkhxhkkk',
      'khggggggabakbbbkbaakbabkbakxghhk',
      'khggggkkabbkbbbkbbbkbaakkbkxgggk',
      'hggggghgkbkgkakgkbkgkbkggkgxgggh',
      'khkkkkkkhkkkkkkhkkkkkkhkkkhxkkkk',
    ],
  };

  S.root_lich = {
    w: 32, h: 32,
    pal: { k: '#1a1410', w: '#e9e1c9', x: '#a99d80', r: '#5a3a1c', s: '#8a6238', a: '#2a2030', b: '#3f3048', e: '#5cff66' },
    px: [
      '......krk.krk.krkkrk............',
      '.......kskkrskrkksk.............',
      '.......krrkrkwrkrrk.............',
      '........krwwwwwwrk..............',
      '.........kwwwwwwwk..............',
      '..kkk...kweewwekwwk.............',
      '.kxwxk..kwkkwwkkwwk.............',
      'kxkxk...kxwwwwwwwxk.............',
      'xkxwwk...kwwkwwwwk..............',
      'kxkwwk...kxxxxxxxk.k............',
      '.kkxwk.kkkxkxkxkxkkwkk..........',
      '...kwwkwwwxxxxxxxwwwwsk.........',
      '...kwwwwwxwssskxkkkwwwk.........',
      '...kxwxxxksswssswwssxwwk........',
      '....kxkkksskkkssssrrkxwwk.......',
      '.....k.ksswwwwwxssrwkkwwwk......',
      '........kkxxxxxxrrrxkkwwwk......',
      '.........kxxxxxxrxxxakwwwk......',
      '.........kasssaaaaraakwwwk......',
      '.........kasssaaarrraawwwk......',
      '........kbasssaaaarraawwwk......',
      '........kaasssaaaarrrawwwk......',
      '........kaassaaaaaarrawwxk......',
      '........kassaaaaaaarrrawk.......',
      '.......kbssaaaaaaaaarrwk........',
      '.......ksssaaaaaaaaarrrk........',
      '.......kssaaaaaaaaaaarrrk.......',
      '......kssaaaaaaaaaaaaarrk.......',
      '..k..ksssaaaaaaaaaaaaaarrk....k.',
      '.ksk.kssaakaaaaaaakaaaaarrk..krk',
      '..kskssaakkaaakaaakaaakarrrkkrk.',
      '...ksssak..kak.kak.kak.karrrrk..',
    ],
  };

  S.wyvern = {
    w: 32, h: 32,
    pal: { k: '#12200e', a: '#2e5a24', b: '#4f8a38', c: '#86c25a', m: '#6b4a2f', n: '#8f6c48', y: '#c9b878', e: '#ffd23a' },
    px: [
      '...................kk...........',
      '.................kkknkkk........',
      '................knknmnnnkk..kkk.',
      '.....kk........knmkmmmmmnnkkaaak',
      '....knnkkkk..kknmknmmmmmmmnkkaak',
      '.....knnnnnkknnmmkmmmmmmmkknkaak',
      '.....knmmmmnkmmmknmmmmmkknnmaaak',
      '......knmmmaammknmmmmmknnmmkaaak',
      '......knmmaaammkmmmmkknmmmmkabak',
      '..kkkkkknaaakmknmmmknnmmmmmkbbk.',
      '.kccceebbaamkknmmkknmmmmmmmabbck',
      'kcbbbkkbbbmknkmmknnmmmmmmmkabbbk',
      '.kybbbbbbbbkknkknmmmmmmmmmkbbbbc',
      '..kkkkbbbbkkkknnmmmmmmmmmmkaabba',
      'kkybbbbbbbbkkkkkkkkkkkkkkk.kkcbk',
      'ccbbbbbbbbbbkbbbbbbkk.......kcbk',
      'kkcaaabbbbbbbkbbbbbbbk......kcbk',
      '..kkkkkkbbbbbkbbbbbbbbk.....kcbk',
      '.......kbbbbbkbbbbbbbbk.....kcbc',
      '.......kkbbbkbybbbbbbbbk....kcbk',
      '........kkyyyyyyyyybbbkbkk.kcbak',
      '........kyyyyyyyyyyybbkbcckcbak.',
      '.........kybbbyyybbbbkaaabcbbk..',
      '..........kbbbybbbbbk.kkkcabak..',
      '..........kcbbkkkbbbk....kkck...',
      '.........kcbbbk.kcbbck.....k....',
      '.........kcbbak.kcbbbk..........',
      '.........kcbbk...kcbbkk.........',
      '........kaaaaak.kaaaaaak........',
      '........kaaaaak.kaaaaaak........',
      '........kaaaaak.kaaaaaak........',
      '.........kkkkk...kkkkkk.........',
    ],
  };

  S.vine_titan = {
    w: 32, h: 32,
    pal: { k: '#0f2410', a: '#2a5c22', b: '#3f8a34', c: '#6fc25a', r: '#5a3a1c', p: '#ff6fae', y: '#ffe26a' },
    px: [
      '..............k.................',
      '.............kpk................',
      '..........kkkpypk...............',
      '.........kkbbapk................',
      '........kbbbabbbk...............',
      '........kbbabbbak..........k....',
      '...k...kbykbbyabbk........kpk...',
      '..kpkkkkkabbbabbk........kpypkk.',
      '.kpypbbbkkkkkbbbkkkkkkkkkkbpabbk',
      'kkbpbbbabkkabbkkbbbabbbakbbabbba',
      'kbakkkabbbkkkkkbbbabpbakbbabkkkb',
      'kakbbakbbakbbabbbabpypbkbabkkakk',
      'kkbbabbkabkbabbbabbbpbbkabkkabbk',
      'kkbabbbkbkkabbbabbbacbbakbkabbba',
      '.kabbbakkkabbbabbbabccabbkkbbbab',
      'kpbbbakkbabbbabbbabbbabbbakkbabb',
      'pypbabkbabbbabbbrrbbabbbabbkacbb',
      'kpbabbkabbbabbbabbbabbbabbbkbcca',
      'kbabbbkbbbabbbabbbabbbabbbakbbab',
      'kabbbkkccabbbabbbabbbabbbabkbabb',
      'abbbakkcccbbabbbabbbabbbcbbkabbb',
      'cbbrrk.kbbbabbbabbbabbbacckkbbra',
      'cbabbk.kbbabbbabbbabbbabbbkkbbab',
      'cabbbk.kbabbbabbbabbbabbbakkbabb',
      'kbbbabkkabbbabbbabbbabbbabkkabbb',
      'kkkkkkkkkkrkkkkkkkkkkkrkkkkakkka',
      'kbabbbckbbabbbk...kkbbabbbkkbbak',
      'kabbbaccbabbback...kbabbbakbbabb',
      'abbbabbkabbbabcck..kabbbabkbabbb',
      'kbbabbkkrbbabbkk...kbbbabrkabbba',
      'kbabbbkrrrabrrk....krrabrrkkbbak',
      '.kkkkkrrrabbbrrk..krrabbbrrrkkk.',
    ],
  };

  S.ghost_jaguar = {
    w: 32, h: 32,
    pal: { k: '#0a3f4c', a: '#127282', b: '#25b3c9', c: '#74e9f6', d: '#dbfeff', e: '#ffffff' },
    px: [
      '................................',
      '................................',
      '..............................k.',
      '................k............kck',
      '...............kck...........kck',
      '...............kck..k........kck',
      '..........k.k..kck.kck.......kck',
      '...k.....kckckkcdckkck..k...kccc',
      '..kckk..kcbkckkcdckkck.kck..kccc',
      '..kccck.dcbccckcdckcdckkck..kccc',
      'd.kcbbckcbbbdcdcdckcdckccck..kcb',
      '..kcbbbcbbbbdckcdckcdckcdck..kcb',
      '..kcbbbbbbdcdcccdcccdcccdckd.kcb',
      '.keebbbebbccdcccdcccdcccdcck.kcb',
      '.kcbbbbbbbbccbbbbbbbbbbbccckkcbb',
      '.kcccbbbbbabbbbbbbbbbbbbbbkkcbbk',
      '.kccccbbbbbbabbbbabbbbabbbccbbk.',
      '.kkkcbbbbbbbbabbbbabbbbabbbbbk..',
      '....kkkkcbbbbbbbbbbbbbbbbbbbbk..',
      '........kabbbbbbbbbbbbbbbabbk...',
      '........kcbbbbbabbbbabbbbbbbk.d.',
      '.......kcbbbbbbbbbbbbbbbbbbk....',
      '.......kcbbbbbbbbbbbbbbbbbbk....',
      '......kcbbbkcbbkkkkkcbbbbbbak...',
      '.....kcbbbbkcbbk...kcbbkcbbbck..',
      '.....kcbbbkcbbbk...kcbbkkcbbbk..',
      '....kcabbkkcbbbk...kcbbkkcbbbck.',
      '...kcbbbbkkcbbk....kcbbk.kcbbbk.',
      '...kcbbbk.kcbbk....kcbbk.kcbbbck',
      '..kcbbbk..kcbbk....kcbbk..kcbbbk',
      '..kcbbbk..kcbbk....kcbbk..kcbbbk',
      '..kcbbk....kkk......kkk....kcbbk',
    ],
  };

  S.sun_idol = {
    w: 32, h: 32,
    pal: { k: '#4a2808', a: '#8a5612', b: '#c98f1e', c: '#f2c53e', d: '#fff4ac', e: '#ff4a1a', f: '#ffa322' },
    px: [
      '................k...............',
      '...............kdk..............',
      '...............kdk..............',
      '..............kccck.............',
      '.....kk.......kccck.......kk....',
      '....kdckkk...kccccck...kkkcdk...',
      '....kadccckkkccccccckkkcccdak...',
      '.....kccccccccccdcccccccccck....',
      '.....kccccccddddbddddcccccck....',
      '.....kaccccdbbbbbbbbbdccccak....',
      '......kcccdbbbbbbbbbbbdccck.....',
      '......kccdbfbbbbbbbbbbbdcck.....',
      '......kcdaafaaaaaaaaafabdck.....',
      '.....kccakfkkbbbbbbkfkkabcck....',
      '...kkcccbkeekbbbbbbkeekbbccckk..',
      '.kkcccccbkeekbbabbbkeekbbccccckk',
      'kddccccabkkkkbaabbbkkkkbbaccccaa',
      '.kkaacccbbbbbbaaabbbbbbbbcccaakk',
      '...kkacaaabbbbaaabbbbbbaaacakk..',
      '.....kccbbbbbaaaabbbbbbbbcck....',
      '......kaabbbbbbbbbbbbbbbaak.....',
      '......kccakdkdkdkdkdkdkacck.....',
      '......kccckkkkkkkkkkkkkccck.....',
      '.....kcccckkdkdkdkdkdkkcccck....',
      '.....kccccccaaaabaaaacccccck....',
      '.....kccccacccccacccccacccck....',
      '....kccaaakkkccccccckkkaaacck...',
      '....kaakkk...kacccak...kkkaak...',
      '.....kk.......kccck.......kk....',
      '..............kacak.............',
      '...............kck..............',
      '...............kak..............',
    ],
  };

  S.death_bloom = {
    w: 32, h: 32,
    pal: { k: '#14081c', a: '#2c1136', b: '#4b1f60', c: '#7d3a9c', w: '#dcd4c0', x: '#9c9480', g: '#234a1e', h: '#3f8a34', e: '#ff2fa8' },
    px: [
      '..............kbk...............',
      '............kkbabkk.............',
      '...........kaaaaaaak............',
      '..kk....k.kaaawwwaaak...........',
      '.kcckkkkbkkkawwwwwaakk.k........',
      '..kccbbbbbbbkwkwkxaakkkakkk..kk.',
      '...kbbbwwwbbbkwxwaakaaaaaaakkbbk',
      '..kkbbwwwwwbbkwaxakaaawwwaaabaak',
      '..kbbbxkwkxbbbkaakkaawwwwwaaaak.',
      '..kbbbbwxwbbbbkaakaaaxkwkxaaaak.',
      '..kbbbbxbxbbbwkkkwaaaawxwaaaaak.',
      '..kkbbbbbbbbkkkkkkkaaawaxaaaak..',
      '...kbbbbbbbwkeeeeekwaakaaaaaak..',
      '...kkbbbbbbkkewweekkkkbkkkaak...',
      '..kbbkwwwkkkkeeeeekkbbbbbbkk....',
      '.kbbbwwwwwbkkeeeeekkbwwwbbbk....',
      '.kbbbxkwkxbbwkkkkkwbwwwwwbbkk...',
      'kcbbbbwxwbbbbkkkkkkbxkwkxbbbk...',
      'cbbbbbxbxbbbbwwwbbbkbwxwbbbbbkk.',
      'cbbbbbbbbbbbwwwwwbbkkxbxbbbbbcck',
      'kkcbbbbbbbbbxkwkxbbbkbbbbbbbbbbc',
      '..kkbbbbbbbkbwxwbbbbkbbbbbbbbbkk',
      '....kkkbkkkbbxbxbbbbkbbbbbbbkk..',
      '.....khkkkbbbbbbbbbkkkbkkkkhhk..',
      '....khhhhkbbbbbbbbbk..kkkhhhhk..',
      '...khhhhhhbbbbbbbbkgkkhhhhhhhhk.',
      '..kkhhhhhhbbbbbkkkkkhhhhhhhhhhhk',
      '..khggggghhbbhkhhkhhhhhhhhgggghk',
      '.khhhhhhhggbggghhkkhhggggghhhhhk',
      '..kkkhhhhhhhhhhkkggkkhhhhhhhhhhh',
      '.....kkkkkhhhkkkgggk.kkhhhhhkkkk',
      '..........kkk..kgggk...kkkkk....',
    ],
  };

  S.storm_elemental = {
    w: 32, h: 32,
    pal: { k: '#141a2c', a: '#2b3550', b: '#4c5b7a', c: '#7889a8', d: '#aab9d2', l: '#fff27a', w: '#ffffff' },
    px: [
      '................................',
      '................................',
      '............k...................',
      '.........kkkckkkl...............',
      '........kddcbddck...............',
      '........kdbbbbbbk.........l.....',
      '.......kcbbbabbadk..............',
      '.......kllbbalbbbk..............',
      '.......kdabbabbbbk...kkkkkk.....',
      '......kcbbbbbbbabkkkkdccccdk....',
      '.....kcbbbbbbbbbbcddccbbbbbck...',
      '....kcbbbbbbaabllbbbbbbbbbbbck..',
      '....kcbbbaabbbbwlbbbbbbbbbbbak..',
      '...kcbbbbabbbbllbbbbbbbbabbbbk..',
      '...kcbbbbbbbbawlabbbbbbbbbaaak..',
      '..kdbbbbbbbbbbblllabbbbababbbck.',
      '.kdbbbaabbbbbbbabwlbbbbbaabbbbck',
      'kcbaaabkcbbbabbblllabbbbbkdbbbbk',
      'kcbbabakcbbbbbblllbbbbbbbkkdbabd',
      'kcbbbbkkdabbbbawlbbbbbbbbkkcbbba',
      'kcbbbbkcbbbbbbblllabbbabadkcbbbk',
      '.kcabadkdbbbbbbblwlbbbbbbkkcbabk',
      '.kdabbbkkcababbbbllbbbbaakcbaabl',
      '.ldbbbak.kkcaaaaaabbbaakkkcbabbk',
      '.kdbbdbk...kaaaaaaaaakk..kcabbak',
      'kdbbbbbdk...kaaaaaaak....kdbbbbk',
      'lkcbbbak....kaaaaaaak....kcbbbak',
      '..kcaak......kaaaaak......kdaal.',
      '..lkkk.......kaaaaak.......kkk..',
      '.............kaaaaak............',
      '..............kaaak.............',
      '..............kaaak.............',
    ],
  };

  S.chaos_ape = {
    w: 32, h: 32,
    pal: { k: '#1c1016', a: '#3a2828', b: '#5e4141', c: '#876161', f: '#b2836f', v: '#b04cf0', e: '#ff3030', y: '#ffe030', w: '#f2eee0' },
    px: [
      '...........................kkkkk',
      '..........................kkabbk',
      '..........................kbbbbb',
      '........................kkkkbbbk',
      '........k..............kkbbkkkkk',
      '.....kkkbkkk..........kbbaabbbkk',
      '...kkbbbbbbbk........kbbbbvbakk.',
      '..kaaaaaaaaaak......kbbbvvbbk...',
      '..kaaaaaaaaaabk..k.kbabvvbbk....',
      '..kkeekfbykbbakkkbkkkkkbbbk.....',
      '..kkeekffkkbvbkbbbbbbbkkbk......',
      '..kkkkkffffbbvkbbbbbbbbbkk......',
      '..kffkkkffffbvvbbbbbbbbbbkk.....',
      '...kwkwkwkfbakvbabvvbbbbbbkk....',
      '...kkwkwkkfbkbbvvvbbvbbbbbbkk...',
      '...kbbbbbkkkbbbvcbbbbvbbbbbkk...',
      '..kbbbbbakbbbcvvccccbbvbabbkbk..',
      '..kaabbbkbbbccvccccccbbbbbvakk..',
      '.kbbbvbbkbbbccvccccccbbbbbvvbbk.',
      '.kabbvbbkabcccvcccccccbbbabvabkk',
      '.kbbvabkbbbbccvvcccccbbbbbavvabk',
      'kbbbvbbkkbabccccvccccbbbbbkbvbbb',
      'kbbvvbk.kkbbbcccvvccbbbbbkkbbbbb',
      'kbbvbbk..kkbbbbacvbbbbbbkkkabbbb',
      'kbbbbbk..kkkkbbbbbbbbbkkk.kbbbak',
      'kbbbbbk..kbbkkkkkbkkkkkbk.kbbbbk',
      'kbkkkbk.kbbbbbbbkkbbbbbbbkkkkkbk',
      'kkabbkk.kbbabbbbkkabbabbakkbbbkk',
      'kaabbbkkkbbbbbbbkkbbbbbbakbbbbbk',
      'cbbbbbbk.kbbbbbk..kbbbbbkbbbbabb',
      'kbbbabkk.kkbbbkk..kkbbbkkkabbbbk',
      'kkaaakk....kkk......kkk..kkaaakk',
    ],
  };

  S.heartwood_sentinel = {
    w: 32, h: 32,
    pal: { k: '#1e1208', a: '#4a2c16', b: '#7a4c28', c: '#a8703c', d: '#d4a066', e: '#ff3a3a', f: '#ffa070', g: '#3f8a3a' },
    px: [
      '.............................k..',
      '............................kdk.',
      '........kkkkkkkkkk.........kkdkk',
      '........kaaaaaaaak.........kdddk',
      '........kbbbbbbbbk.........kdddk',
      '........kbbbbbbbbk.........kdckk',
      '........kkeekkekbk........kdcck.',
      '........kkkkkkkkbk........kdcck.',
      '........kbbababbbk.kk.k...kdcck.',
      '....kkkkkbbbbbbbbkkggkdkkkkdcck.',
      '..kkakgdkbbbbbbebkbkgdcddkkdck..',
      '.kbabaggkkkkkkkkkkkdccckddkdck..',
      '.kbaaabkbkkdkbkkkbedckkbkkkdck..',
      'kbbaaaabkbkekkeeekkdckbbbkkdck..',
      'kbbababbkbbkkeefeekkkbbbbbkdkk..',
      'kbbababakbkkkefffekkkkbbbbkdk...',
      'kbbacabbkbkbkeefeekbbkabbbkkk...',
      'dbbcccbbbkkbbkeeekbebkkbbbbkk...',
      'kbaacabbkbkabbkkkbbbbbkbbbbkk...',
      'kbbabaabkkbaebbbbbbbbbkbbbbbk...',
      'kbbababbkkabbbbbbabbbbkkbabkak..',
      'kbbababbkkbbbbbbbbbbbbkkkbkkk...',
      '.kbababkaakkkkkkkkkkkkakakkk....',
      '.kbababkaaaaaaaaaaaaaaaakkk.....',
      '..kkbkkkaaaaaaaaaaaaaaaak.......',
      '....k...kkkkkkkkkkkkkkkk........',
      '.........kbbbbbkkbbbbbk.........',
      '.........kbbbabkkbbbbbk.........',
      '........kkkkkkkkkkkkkkkk........',
      '........kaaaaaakaaaaaaak........',
      '........kaaaaaakaaaaaaak........',
      '........kkkkkkkkkkkkkkkk........',
    ],
  };

  S.nightmare_moth = {
    w: 32, h: 32,
    pal: { k: '#100a1a', a: '#1e1230', b: '#33204f', c: '#4f3475', w: '#d8d1c2', x: '#8f8878', p: '#c95cff', e: '#ff3fd0', f: '#5a4060' },
    px: [
      '.........kkk.........kkk........',
      '........kxxxkk.....kkxxxk.......',
      '.........kxxkxk...kxkxxk........',
      '........kkxkxk.....kxkxkk.......',
      '......kkcbkkxxk...kxxkkbckk.....',
      '...kkkbbbbbkkkxk.kxkkkbbbbbkkk..',
      '.kkbbbbbbbbkkkxxkxxkkkbbbbbbbbkk',
      'kbbbbbbbbbbbk.kxfxk.kbbbbbbbbbbb',
      'kbccbwwwwbbbbkfffffkbbbwwwwbbccb',
      'kbbbwwwwwwbbbkeeffekbbwwwwwwcbbb',
      'kbbbwkwwkwbbbkfffffkbbwkwwkwbbbb',
      'kbbbxwkwwxccbbkfffkbbcxwkwwxbbbb',
      'kbbbbwxwwbbbcckkkkkccbbwxwwbbbbb',
      'kbbbbxbxxbcccckfffkccccxbxxbbbbb',
      'kbbcccccccbbbbfffffbbbbcccccccbb',
      'kbbbbbbbbbbbbkfffffkbbbbbbbbbbbb',
      'kbbbbbbbbbbbbkfffffkbbbbbbbbbbbb',
      '.kkbbbbbbbbbbkfffffkbbbbbbbbbbkk',
      '...kkbbbbbbbbkfffffkbbbbbbbbkk..',
      '....kkkbbbbbkkfffffkkbbbbbkkk...',
      '.p.kaaaakkkaakfffffkaakkkaaaak..',
      '..kaaaaaaaaaakkkkkkkaaaaaaaaaakp',
      '..kaaaaakkkaakfffffkaakkkaaaaak.',
      '..kaaaakccckakfffffkakccckaaaak.',
      '..kaaaakcpckaakkkkkaakcpckaaaak.',
      '..kaaaakccckaakfffkaakccckaaaak.',
      '...kaaaakkkaaakfffkaaakkkaaaakp.',
      '...pkkaaaaaaakkkkkkkaaaaaaakk...',
      '.....kkkkakkkk..k..kkkkakkkk....',
      '.........k.............k...p....',
      '......p.....p...p...............',
      '....................p...........',
    ],
  };

  S.fossil_drake = {
    w: 32, h: 32,
    pal: { k: '#1e1a14', a: '#4a4238', b: '#7a6e5a', c: '#aa9e82', d: '#d4caab', e: '#ffb020', f: '#ffe08a' },
    px: [
      '................................',
      '................................',
      '.........................kk...kk',
      '........................kbbkkkbb',
      '............k..........kbbbkbbbk',
      '...........kbk........kbbbbbbkk.',
      '..........kbbk.......kbbbbbkk...',
      '......k..kbbkk......kbbbbkkkkkkk',
      '...kkkckkbbkbbk....kbbbbbbbbbbbb',
      '..kccccccbkbbk.....kbbbbbkkkkkkk',
      '.kcccceekcbbk.k..kkbbkbbbbbk....',
      '.kcccbkfkcckkkdkkdbbbkkbkkbbkk..',
      'kdckccccccckdkdddcccckkkbkkkbbk.',
      'dcbccccbcckccdcccccccddkkbk.kkbk',
      'kdkdkdcckkbcccccbcccccckkbbk..k.',
      '.kkkdcbck.kdbbbckdbcbccdkkbk....',
      'kkdddcccdk.kkdkdkdkdkdccdkkbk.k.',
      'ddbbbbbbbk.kdbdcdcdcdcbccdkk.kdk',
      'kkkkkkkkk..kdbcbcbcbcbkdcck..kdk',
      '...........kdkdkdkdkdkdccck..kdd',
      '...........kdkdkdkdkddbccck..kdk',
      '...........kddcdbdbdccccccdk.kdc',
      '...........kkbkckdkdkccccckk.kdc',
      '...........kccccdbdbccccccddkdbb',
      '...........kccckbkdkdcbckckbdkbk',
      '..........kccck.k.k.kkbcbkbbcbk.',
      '..........kccck......kccckkkdk..',
      '.........kccbk........kccck.k...',
      '.........kccck........kccck.....',
      '.........kccck........kccck.....',
      '........kccck..........kccck....',
      '.......kdbbbbk........kdbbbbk...',
    ],
  };

  S.bramble_king = {
    w: 48, h: 48,
    pal: { k: '#120c0a', a: '#3a2618', b: '#5e3e22', c: '#8c6238', g: '#2e5a24', h: '#4f8c38', y: '#e6b642', z: '#8a6410', e: '#ff2a2a' },
    px: [
      '...............kyk..kyk.........................',
      '...........k...kybkkbyk...k..........k..........',
      '..........kyk..kzbkkbzk..kyk........kkk......k..',
      '..........kybk.kbbkkbbk.kbyk.k.....kabkk....kkk.',
      '..........kzbk.kbbkkbbk.kbzkkak....kbaakk..kaak.',
      '...........kbbkkbbkkbbkkbbkkaabk..kbaaaakkkaabk.',
      '............kbk.kbkbbkkkbk.kabaakkbaaaabakaabaak',
      '............kbbkbabbbabbbkkabaaaakakaabaaakbaaak',
      '............kzyyyyyyyyyyyzkbakaabaaakbaaaabkaaak',
      '............kzzzzzzzzzzzzzbaaakbaaaabkaaabaakabk',
      '.............kaaaaaabbabbkaaaabkaaabaakagaaaabak',
      '............kaeekaaeekbbbakaabaakabaaaabghaabakk',
      '............kbkkkaakkkbbabkagaaaabaaaabakaabaaak',
      '............kbaaaaaaabbabbkbghaabakaabaaakbaaaak',
      '.............kaaaaaaababbkaakaabaaakbaaaabkaaabk',
      '..........kkkkkkkkkkkabbbkaaakkaaaabkaaabaakabak',
      '........kkbbakkbaabbabbbkkakkkbkkgbaakabaaaabaak',
      '......kkbbbabkkkbbbabbbkkbkabbbabghaaabaaaabakak',
      '......kbbbabbkabkkkbkkkabakbbbabbbakabakaabaaakk',
      '.....kbbbabbbkbaabakbaabaabbbabbbabkbaaakbaaaabk',
      '.....kbbkkkbabaabaabaabaakbbabkkkbbbkaaaakaagbak',
      '.....kbkbbbkbbabaabaabaabkbabkbabkbkaaaaaakaghak',
      '......kbbbabkbkaabaabaabakbbkbabbbkkkaaaaaabaaak',
      '.....kbbbabbkbkabaabaabaabkbkabbbabkkaaaaabakaak',
      '....kbbbabbbkkkbaabaabaakbbkkbbbabbbkkkaabaaakbk',
      '...kbbcabbbkkbkaabaabaabkbbabkbabcbabbkkbaaaabkk',
      '..kbbbabbgkbbbakbaabaabakbabbbgbbbabbbakkaaabaak',
      '.kbbbabbbghbbabbkabaabkkbabbbaghkabbbabbkkabaaak',
      '.kbbabbbkkbbabbbakaakkbbabbbabbbkkbbabbbkabaaaak',
      '.kbabbbk.kbabbbabbkabbbabbbabbbabkkabbbakbakaabk',
      '.kabbbgkkcabcbabbbabbbabbbabbbcbbbkbbbabcaaakbak',
      '.kcbbaghkabbbabbbabbbabbbabbbabbbakkbkkkbkaabkak',
      'kkbbabkkkbbbabbbabbbabbbabbbabbbabkkkbbbkkabaakk',
      'kbbkbbkkkbbabbbabbbabbbabbbabbbabbkkbbbabkkkkkkk',
      'kbkbkbkabbabbbabbbabbbabbbabbbabbbkbbbabbbgaaaak',
      'kkbbbkkkbabbbabbbabbbabbbabbbabbbabkbabbbkghaaak',
      'ckkbabkkabbbabbbabbbabbbabbbabbbabbkgbbbkkaaaaak',
      'kkkkkbbakkkkkkkkkkkkkkkkkkkkkkkkkkkaghkkaaaaaaak',
      'kkbkkkbbbkbbbbbbbbkkkbbbbbbbbkakkaaaaaaaaakaaaak',
      'kkbkbbkbkkbbbbbbbbkbkbbbbbbbbkbbbkaaaaaakkbkaaak',
      'ckbbkbbkckbbbbgbbbkbkbbbgbbbbkbbabkkcakbabbbkaak',
      'kkbbkbbbkkbbbbghbbkakbbbghbbbkbabbbakkbabbbabkkk',
      '.kbbbkbkkkkkkkkkkkkkkkkkkkkkkkkkbbabbbabbbabbbk.',
      'kakbkakkaaaaaaaaaaakaaaaaaaaaaakbabbbabbbabbbabk',
      'kbbkabbkaaaaaaaaaaakaaaaaaaaaaakabbbabbbabbbcbbk',
      'kbcabbbkaaaaaaaaaaakaaaaaaaaaaakbbbabbbabbbabbbk',
      'kbabbbakkkkkkkkkkkkkkkkkkkkkkkkkbbabbbabbbabbbak',
      'kaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaak',
    ],
  };

  S.mother_of_fangs = {
    w: 48, h: 48,
    pal: { k: '#120a18', a: '#241536', b: '#3d2559', c: '#5c3b7d', g: '#2a5a30', h: '#3f8a45', i: '#7ac06a', v: '#8fff4a', w: '#ebe6da', e: '#ff3030' },
    px: [
      '........kkkkkk........................kkkkkk....',
      '.......kvgegggk.....................kkggeggvk...',
      '........kgggggk....................kkkgggggk....',
      '........kgggggkk.................kkggkgggggk....',
      '.........kkkkkggk...............kgggggkkkkkkkkkk',
      '...........kggggkk.............kgggggggk.kgegggv',
      '............kggggk............kggggggkk..kgggggk',
      '.kkkkk......kkggggk..........kkggggkk....kgggggk',
      'kgehghk......kgggggk.........kggggkk......kkkkkk',
      'vhhghhk.......kggggk........kgkgggk........kgggk',
      'khghhgk.......kkggggk...k..kkgggkk....k....kgggk',
      '.kkkkk.........kggggkk.....kkkkkbkkkkk.....kgggk',
      '.khghk..........kggggk...kkbbbbbkbbbbbkk...kgggk',
      '.kghhkk.........kggggk.kkbbbbbbbbbbbbbbbkk.kgggk',
      '.khhghk..........kgggkkkbbcccccccccccccbbkkkkggk',
      '.khghhk........k..kkkkbbabacccccccccccbbbbbkgggk',
      '..khhghk...kkkkbkkkkkkabbbabcccccccccbbbbbbkkggk',
      '..khghhk.kkbbbbbbbbbkkbbbbbbbcccccccbbbbbbbbkgk.',
      '...khhghkkbbbkbbbbbbbkkbbbbbabcccccbbbbbbbaakk..',
      '...khghhkkbekebbbbabbbkbbbbbbbcccccbbbbbbbbbbk..',
      '...kkhhgeekkkbkbbbbbbbbkbbbbbbbcccbbbbbabbbbbk..',
      '....khgheekkkbebbbbbbbakbbbbbbbbcbaabbbbbbbbbk..',
      '.....khhkkkghkbkabbbbbbakbbbbbbcccbbbbbbbbbabbk.',
      '......kkhhghegkebbbbbbaakbbabbbbcbbbbbbbbbbbbk..',
      '......kkkehhkhkbbbbbbbbbkbbbbbbcccbbbbabbbbbbk..',
      '.......kbkkgkkkbbaabbbbkbbbbbbcccccbbbbbbbbbbk..',
      '.......kabkkhghkbbbbbbakbbbbbbcccccbbbbbbbbbbk..',
      '........kkkkkkkkkbbbbbkbabbbbcccccccbbbbbabkk...',
      '.......kwwwwhwwwwkkkbkkbbbbbcccccccccbbbbbbkk...',
      '.......kwwwwhwwwwhhgkkbbbbacccccccccccbbabbk....',
      '......khwwwhgwwwkhghk.kkakkkcccccccccccbbkk.....',
      '.....khhwwwkkkwwhghhk..kkhghkbbbbbbbbaabkk......',
      '....kkhghwwk.kwwghhkk.k.kghhkbbbkbbbbbkkk...k...',
      '....khghhwk..kwghhgk...kghhgkkkkbkkkkkggkk......',
      '...kkghhkwk..kwhhgkk...khhghk...k...kggggk......',
      '...kghhgkv...kvhghk....khghhk.......kkggggk.....',
      '..kkhhgkkv..kkhghkk....kghhk.........kggggk.....',
      '..khhghk....khvhhk....kghhgk..........kggggk....',
      '.kkhghkk.v..kgvhkk....khhghk..........kggggk....',
      '.khghhk....kghhgk.....khghhk...........kggggk...',
      '.kghhkk....khhghk.....kghhk............kggggk...',
      'kkkkkk.....khghhk.....khhghk...........kggggk...',
      'iehghk....khghhk......khghhk............kggggk..',
      'vhghhk....kghhgk.......khhgk............kgkkkkk.',
      'ighhgk..kkkkkghk.......khgkkkkk..........kggeggk',
      'kkkkk..khehhgkk........kgkhgehgk.........kgggggv',
      '......kvghhghkk.........kkghhghvk........kgggggk',
      '.......kgggggk..........kkgggggk..........kkkkk.',
    ],
  };

  S.vine_warden = {
    w: 48, h: 48,
    pal: { k: '#0e160c', a: '#3a2614', b: '#6a4526', c: '#9a6a3c', d: '#c89860', g: '#2f6e2a', h: '#5aa848', e: '#6fff5a', f: '#d8ffc0' },
    px: [
      '...................kkakk........................',
      '..................kaaaaak...........kkkkkkkkkkkk',
      '.................kaaaaaaak..........kbaabaaaaaba',
      '..............kkkaaaaaaaaakkk.......kaabaabaabaa',
      '..............kaaaaaaaaaaaaak.......kabaaaaabaaa',
      '.............kaaaaaaaaaaaaaaak......kbaabaabaaba',
      '..............kkkkkkkkkkkkkkk.......kaabaabaabaa',
      '..............kabbbbbbbbbbbbk.......kabaabaaaaab',
      '..............kkkeeekkkeekbak.......kbaabaabaaba',
      '..............kkkkkkkkkkkkbbk.......kaabaaaaabaa',
      '..............kbbbbabbbbbabbk.......kabaabaabaab',
      '.......kkk.k..kaaaaaaaaaaaabk.......kkkkkkkkkkkk',
      '....kkkdddkhk.kbbbbbbbbbbbbbk.......khkkdkkkk...',
      '...kdhdcccdhhkkaaaaaaaaaaaabkkkkkkkkkhhdcddhkk..',
      '..kdchhccccccdkbbbbbbbbbbabakbbbbbkddcccccchhdk.',
      '.kdccccccccggckkkkkkkkkekkkkkbabbbkdcccccccccck.',
      '.kdcccccccccggdkbbabbbbaabbbbbabbkgcccccccccccdk',
      '.kdccccccccccggkbbabbbaaabbaababbggcccccccccccck',
      '.kdccccccccchcggbbabbbkkkbbbaaabgghcccccccccccck',
      '.kdcckkkkkdchhcggbabkkkkkkkbbbabgbhhccckkkkkdck.',
      '..kdkbbbbbkdcckbgeakkkeeekkkbbaggbkdcckbbbbbkdk.',
      '...kkbbbbbkdckbabggkkkeeekkkbbggbbbkkdkbbbbbkk..',
      '...kbbbbbbkkkbabbhgkekfffkekkbgabbbbkkkbbbbbbk..',
      '...kabbbbbkbababbhhkekfffkekkhggabaaabkbbbbbbk..',
      '...kbbbbbbkkaabbeggkekfffkekkhegbbbbakkbggbbbk..',
      '..kbbabbbkkkabbbbgkkekfffkekkbagbbabakkbbggbbk..',
      '..kbbbbabk.kabbbbgkkekeeekekkbaggbbbakbkbbgghbk.',
      '.kkgbabbbk.kabbbggakkkeeekkkbbaggbbbakbkbbkghhk.',
      '.kabgbbbk..kabbbggakkkeeekkkbeabgbabakbkkkkbggk.',
      '.kbabgbbk..kababgbabkkkkkkkbbbabggbbakbkkbbbbbkk',
      '.kbbbagbk..kdbbbgbabbbkkkbbbbbabggbbabbkabbbabak',
      '.kbbabbgk...kabbbbabbaaaaabbbbabbgbbkkbkabbbbbbk',
      '.kabbbgghk..kbbbababbbabaabbbbabbbbbkkkkbbbbbbbk',
      '.kbbbbgbhhk.kbbabbabbbbeabbbbbaabbbbk..kkaabbbkk',
      '.kbbbgabkk..kbgbbbbbbbbbbbbbbbabbbbbk...kkkbkkk.',
      '.kbbggbbk...kkkgkkkkkkkkkkkkkkkgkkkk......kkk...',
      '.kbbgkkbk...kbbbgbbbbk....kbbbggbbbk............',
      '..kkbabkk...kbbbbgbbk......kbbgbbabk............',
      '.kbbbbbbbk..kbbbbbgbk......kbgbbbbbk............',
      '.kbbbbbbbk.kbbbbabbgk......kggbbbbbbk...........',
      '.kbbbbbbbk.kbbbabbghk......kgbbbbabbk...........',
      '.kbbbbbbak.kbbbbbgbhhk.....khgbbbbbbk...........',
      '.kbbbbbbbk.kbbkkgabbk......khhgkkkbbk...........',
      '..kkbbbkk..kkkkgkkbk........kkkgaakkk...........',
      '....kkk..kkkakaaaakk.......kkkkagaaaakkk........',
      '......kkkaaakkkaaaakk....kkkaakkaaaaaaaakkk.....',
      '.....kkaaaakkakkaaaakk..kkaaaaakkkaaaaaaaakk....',
      '.....kaaaaakaaakkaaaak..kaaaakkkaakkkaaaaaak....',
    ],
  };

  S.heart_of_jungle = {
    w: 64, h: 64,
    pal: { k: '#2a0a14', a: '#7a1030', b: '#b8204a', c: '#e8407a', v: '#ffd0e8', r: '#3a2010', s: '#6a4020', g: '#2f6e2a', h: '#5aa848', y: '#ffe066' },
    px: [
      '................................................................',
      '................................................................',
      '..............................k.v...............................',
      '.............................kvk................................',
      '............................kvvvk.......k.......................',
      '...........................kvvyvvk.....kvk......................',
      '........................k...kvvvk.....kvvvk.....................',
      '......................kkgkk..kvk.....kvvyvvk....................',
      '............k.......kkgggggkkkhk......kvvvkkkkk.................',
      '...........kvk....kkhgggggggghhk....kkccvcccccckk...k...........',
      '..........kvvvk.kkghhggkkkkgghggkkkkccbbbbbbbbbcckkkvkkkk.......',
      '........kkvvyvvkggghgkkbbvbkkggggggkbcvbbbbcbbbbbccvvvrrrk......',
      '.......krrrvvvgggggkkbbbbvvbbkkkggggkhbbbbbbbbabbbvvyvvrrk......',
      '.......krrrkvggggkkccccbbbvbbbbbkkgkhhbbbbbbbbbbbbbvvvrrrk......',
      '.......krrrrkggkkvvcccccbbbvvbbbbbkbhbbbbbbbbbbbbbbbvrrrrk......',
      '.......krrrkgggkvvvvcccccbbbvbbbbvbbbbbbbbbbbbbbbbbbkrrrk.......',
      '........krrkggkvvvvccccccbbbvbbbbvbbbbbbbbbbbbbbbbbakrrrk.......',
      '........krkkghkcvcccccccccaacvbbvbbbbbbbbbcbbbbbbbbkrrrrk.......',
      '...v....krkghhcccccccccccbbabvbvvbbbbbbbabbbbabbbbbkrrrk........',
      '.........kkghkcccccccccccbbbbvcvbbbbcbbbabbbbbbbbvbkrrrk........',
      '.........kggkkkcccccccccbabbbbvvbbbbbbabbbbbbbcbvvkrrrrk.....v..',
      '.........kggkrkccccccccbbbbbbbvbbababbbabbbbbbabvbkrrrkk........',
      '........kgggkrkbvccccbaaabbbbbbbbbbbabbbbbbbbbbbvbkrrrkak.......',
      '........kggkrrkbbvvbaaaaaaabbbbbbbbbbbbaaaaabbbvbbkrrrrk........',
      '.......kgggkrkbbbbvvaabbbbaaabbbbcbbbaaaabaaaabvbbbkrrrk........',
      '........kgkrrkbbbbaavbbbbbbbaabbbbbbaaabbbbbaavbabbkrrrrk.......',
      '........kkrrkbbbbbbbbbbbkbbbbbbbbbbabbbbbbbbbbvbbbvbkrrrk.......',
      '.......krhrrkvbbbbbbbkkkkkkkbbbbbbbbbbbkkkkkbbbbbbvakrrrrk......',
      '.......khhrkbvvbbbbbbkkkkkkkbbbbbbbbbbkkkkkkkbbbvvvbbkrrrk......',
      '.....kkrhrrkbbvbbbbbkkyyyyykkbbbbbbbbbkyyyykkbbbvbbbbkrrkgk.....',
      '....kvkrrrkcvbbvvbbbbkkkkkkkbbbbbbbbbbkkkkkkkbvvvbcbbakkgggk....',
      '...kvvvrrrkvcbcabvvbbkkkkkkkbbbbbbbbbbbkkkkkbbvbbbbbakkgggkvk...',
      '..kvvyvvrkvkkcbbcbvvbbbbkbbbbbbbbbbbbcbcbbbcbvvbbbbakkkggkvvvk..',
      '...kvvvrrrk..kcabbbbbbbbbabbbbbbbbabbbbbbbbbbbbbbaak.kggkvvyvvk.',
      '....kvkrrrk...kkcbbbbbbbbbbbcbaabbbbbbbbcbbbbabbakk.kgggkrvvvk..',
      '.....kkrrrkk....kcbbbbbbbbbbbbbbbbbbbbbbbabbbbbak..kgggkrrkvk...',
      '......krrrrk...kkkcbbbbbbbbbbbbabbbbbbbbbbbbbbak..kgghkrrrkk....',
      '.......krrrk..kvvkcbbbbbbbbbbbbabbbbbbcbbkbbbbakkkkghhrrrk......',
      '.......krrrrk..kvvvcbbbbkbcbbbbcbabbbbbbkkkbbakkvkgghkrrrk......',
      '.......kkrrrk...kkvvcbckkkbbbaaaabbbbaaakkbbakkvkgggkrrrkk......',
      '........krrrkk....kkvvbbkkaaakkkvaacaaakkbbakkvkgggkkrrrk.......',
      '........krrrrk......kkvbbbkkvkkkkkaaakkkbbakkvkgggkkrrrrk.......',
      '.........krrrk........kvvbbkbbbcbkkkvkbbbakkvkgggk.krrrk........',
      '.........krrrkkkk......kvvvbabcbvbbkbbbbakvvkgggk..krrrk........',
      '.....v....kkkkggkkkkk...kcvvbbcbvbbbbbvvvvkkgghk....kkk.........',
      '.............kggggkhkk...kcbvbbbvbbbvvvkkkkgghhsk...............',
      '..............kkgghhkkkk..kcbbbbvbbbbak..kggghsrk...........v...',
      '...............kvkhggkkskkkcbbbbvbbbbakkkgggksrsk...............',
      '..............kvvvkggggkkskkbbbabbbbckkkgggksrskvk..............',
      '.............kvvyvvkkggggkrkkbbbbcbbkkrskgksrkkvvvk.............',
      '............kkkvvvsrkkkggkssrkkbbbkksrssrkskksvvyvvkkk..........',
      '.........kkkrssrvsrssrkkkksrssrkkkssrssrskkssrsvvvsrsskkk.......',
      '.......kkssrssrssrssrsskksrssrssrssrssrskkssrssrvsrssrssrkkk....',
      '....kkkrssrssrssrssrssrsskksrssrssrssrkkrssrssrssrssrssrssrskkk.',
      '..kkssrssrssrskkkkkkkkkkksskksrssrsskksrkkkkkkkkkkkrssrssrssrssk',
      '.krssrssrsskkkkkkrssrkkrssrsskksrskkssrssrkkrssrkkkkkkkkrssrssrs',
      'krssrsskkkkkkkssrssrkkrssrssrskkkkkssrssrsskksrssrkkk...kkkkkrsk',
      '.kskkkkkkkssrssrsskksrssrssrsskkkkksrssrssrsskksrssrskkk.....kk.',
      '..kk.kksrssrssrskkssrssrssrskksvkkskksrssrssrsskksrssrskkk......',
      '...kkssrssrssrskkssrssrssrkkrssk.krsskksrssrssrskkssrssrsskkk...',
      '.kkrssrssrssrkkrssrssrskkksrsskk..ksrsskkkrssrssrskkssrssrssrkkk',
      'ksrssrssrkkkksrssrssrkk.ksrsskk...kkssrskkkkrssrssrskrssrssrssrs',
      'srssrskkk..ksrssrsskk...krsskk......krssrk..kkrssrssrkkkssrssrss',
      'kskkkk....ksrssrkkk....krsskk........kkrssk...kkkssrssk.kkkkkksr',
    ],
  };

})();
