// js/sprites/ui.js — UI icons, item/potion/status icons and jungle decorations.
// Text pixel grids; see docs/ART_SPEC.md. Plain script (not a module).
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  S.node_battle = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      s: '#eef2f6',
      m: '#a9b4c2',
      d: '#5c6878',
      g: '#f0c040',
      o: '#a8721c',
      b: '#6b4a2f',
    },
    px: [
      '.kk..................kk.',
      '.ksk................ksk.',
      '.ksmk..............kmsk.',
      '..ksmk............kmsk..',
      '...ksmk..........kmsk...',
      '....ksmk........kmsk....',
      '.....ksmk......kmsk.....',
      '......ksmk....kmsk......',
      '.......ksmk..kmsk.......',
      '........ksmkkmsk........',
      '.........ksmmsk.........',
      '..........ksmk..........',
      '.........kmssmk.........',
      '.....kggkmskksmkggk.....',
      '.......kggk..kggk.......',
      '.........kggggk.........',
      '......kbbkkggkkbbk......',
      '.....kbbk.kkkk.kbbk.....',
      '....kbbk........kbbk....',
      '...kbbk..........kbbk...',
      '..kggk............kggk..',
      '..kook............kook..',
      '...kk..............kk...',
      '........................',
    ],
  };

  S.node_elite = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      w: '#f4f1e8',
      n: '#cfc7b6',
      s: '#8e8676',
      g: '#f6c94a',
      o: '#ad7a1c',
      r: '#e83a4a',
      e: '#2a1030',
    },
    px: [
      '........................',
      '.....kk....kk....kk.....',
      '.....kgk..kggk..kgk.....',
      '.....kggkkggggkkggk.....',
      '.....kgggggrrgggggk.....',
      '.....koogggrrgggook.....',
      '.....kkkkkkkkkkkkkk.....',
      '....kwwwwwwwwwwwwwwk....',
      '...kwwwwwwwwwwwwwwwwk...',
      '...kwwwwwwwwwwwwwwwwk...',
      '...kwwkkkkwwwwkkkkwwk...',
      '...kwkeeeekwwkeeeekwk...',
      '...kwkeeeekwwkeeeekwk...',
      '...kwwkkkkwnnwkkkkwwk...',
      '....knnnnnknnknnnnnk....',
      '....knnnnnnnnnnnnnnk....',
      '.....knnnnnnnnnnnnk.....',
      '......kkkkkkkkkkkk......',
      '......kwkwkwwkwkwk......',
      '......kwkwkwwkwkwk......',
      '......kskskssksksk......',
      '......kkkkkkkkkkkk......',
      '........................',
      '........................',
    ],
  };

  S.node_boss = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      w: '#f4f1e8',
      n: '#cfc7b6',
      s: '#8e8676',
      h: '#c8925a',
      d: '#8a5a2a',
      e: '#2a1030',
      r: '#ff3a3a',
    },
    px: [
      '.kk..................kk.',
      'khhk................khhk',
      'khhhk..............khhhk',
      '.khhhk............khhhk.',
      '..khhhk..kkkkkk..khhhk..',
      '..kdhhhkkwwwwwwkkhhhdk..',
      '...kdhhkwwwwwwwwkhhdk...',
      '....kddkwwwwwwwwkddk....',
      '.....kkwwwwwwwwwwkk.....',
      '....kwwwwwwwwwwwwwwk....',
      '...kwwwwwwwwwwwwwwwwk...',
      '...kwwkkkkwwwwkkkkwwk...',
      '...kwkeeeekwwkeeeekwk...',
      '...kwkerrekwwkerrekwk...',
      '...kwkeeeekwwkeeeekwk...',
      '...kwwkkkkwnnwkkkkwwk...',
      '....knnnnnknnknnnnnk....',
      '.....knnnnnnnnnnnnk.....',
      '......kkkkkkkkkkkk......',
      '......kwkwkwwkwkwk......',
      '......kwkwkwwkwkwk......',
      '......kskskssksksk......',
      '......kkkkkkkkkkkk......',
      '........................',
    ],
  };

  S.node_rest = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      b: '#6b4a2f',
      c: '#9c7048',
      r: '#e8502a',
      o: '#f6a02a',
      y: '#ffe066',
      w: '#fff6c8',
    },
    px: [
      '........................',
      '...........k............',
      '..........krk...........',
      '..........krk...........',
      '.........krork..........',
      '.....k...krork...k......',
      '....krk.krooork.krk.....',
      '....krk.kroyork.krk.....',
      '....krk.kroyyork.krk....',
      '...korkkroyyyyorkkrok...',
      '..korkkroyywwyyorkkrok..',
      '..krrooyyywwwwyyyoorrk..',
      '..krooyyywwwwwwyyyoork..',
      '...krooyyywwwwyyyoork...',
      '....krrooyyyyyyoorrk....',
      '.....kkrroooooorrkk.....',
      '...kkkkkkkkkkkkkkkkkk...',
      '..kcccccccccccccccccck..',
      '..kbbbbbbbbbbbbbbbbbbk..',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      'kccbccccccccccccccccbcck',
      'kbbbbbbbbbbbbbbbbbbbbbbk',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      '........................',
    ],
  };

  S.node_treasure = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      b: '#5a3a22',
      c: '#8a5a30',
      d: '#c08a50',
      g: '#f6c94a',
      o: '#ad7a1c',
      y: '#fff2a0',
    },
    px: [
      '........................',
      '........................',
      '........................',
      '....kkkkkkkkkkkkkkkk....',
      '...kddddddddddddddddk...',
      '..kddbbbbbbbbbbbbbbddk..',
      '..kdbbbbbbbbbbbbbbbbdk..',
      '..kdbbbbbbbbbbbbbbbbdk..',
      '..kdbbbbbkkkkkkbbbbbdk..',
      '..kdbbbkkgyggygkkbbbdk..',
      '..kkkkkgggyggggyggkkkk..',
      '..kddggggggggggggggddk..',
      '..kdccgoccccccccgoccdk..',
      '..kggggggggggggggggggk..',
      '..kccccccckkkkccccccck..',
      '..kccccccckggkccccccck..',
      '..kccccccckgokccccccck..',
      '..kccccccckkkkccccccck..',
      '..kbbbbbbbbbbbbbbbbbbk..',
      '..kbbbbbbbbbbbbbbbbbbk..',
      '..kkkkkkkkkkkkkkkkkkkk..',
      '........................',
      '........................',
      '........................',
    ],
  };

  S.node_shrine = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      s: '#6e7a86',
      t: '#9aa7b3',
      u: '#cbd5de',
      g: '#5ef2d0',
      y: '#eafff8',
    },
    px: [
      '........................',
      '......kkkkkkkkkkkk......',
      '.....kuuuuuuuuuuuuk.....',
      '..g..kuttttttttttuk.....',
      '.....kkkkkkkkkkkkkk.....',
      '.......kttttttttk.......',
      '..g....ktggttggtk.......',
      '.......ktggttggtk.......',
      '.......kttttttttk...g...',
      '.......ktsggggstk.......',
      '.......kttssssttk.......',
      '.......kkkkkkkkkk.......',
      '......kttttttttttk......',
      '...g..ktsgttttgstk......',
      '......ktgygttgygtk......',
      '......ktsgttttgstk..y...',
      '......kttssttssttk......',
      '......kkkkkkkkkkkk......',
      '....kuuuuuuuuuuuuuuk....',
      '....kttttttttttttttk....',
      '....kssssssssssssssk....',
      '....kkkkkkkkkkkkkkkk....',
      '........................',
      '........................',
    ],
  };

  S.node_event = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      p: '#f6e6ba',
      q: '#dcc48e',
      r: '#a88a52',
      i: '#6a3aa8',
    },
    px: [
      '........................',
      '..kkkkkkkkkkkkkkkkkkkk..',
      '.kqppppppppppppppppppqk.',
      '.kqrrrrrrrrrrrrrrrrrrqk.',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      '...kppppppppppppppppk...',
      '...kppppppppppppppppk...',
      '...kpppppkkkkkkpppppk...',
      '...kppppkkiiiikkppppk...',
      '...kpppkiikkkkiikpppk...',
      '...kpppkkkpppkiikpppk...',
      '...kppppppppkiikkpppk...',
      '...kpppppppkiikkppppk...',
      '...kppppppkiikppppppk...',
      '...kppppppkiikppppppk...',
      '...kppppppkkkkppppppk...',
      '...kppppppkiikppppppk...',
      '...kppppppkkkkppppppk...',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      '.kqppppppppppppppppppqk.',
      '.kqrrrrrrrrrrrrrrrrrrqk.',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      '........................',
      '........................',
    ],
  };

  S.node_merchant = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      b: '#7a4e28',
      c: '#b07a44',
      d: '#dcae78',
      g: '#f6c94a',
      o: '#ad7a1c',
      y: '#fff2a0',
      r: '#c83a4a',
    },
    px: [
      '........................',
      '..........kkkk..........',
      '.........kcddck.........',
      '.........kcccck.........',
      '..........krrk..........',
      '........kccbbcck........',
      '.......kcdccccbck.......',
      '......kcddccccccbk......',
      '.....kcdddccccccbbk.....',
      '....kccddcccccccbbbk....',
      '....kcddccccccccbbbk....',
      '...kccdcccccccccbbbbk...',
      '...kcccccccccccccbbbk...',
      '...kccccccccccccbbbbk...',
      '...kbccccccccccbbbbbk...',
      '....kbbccccccbbbbbbk....',
      '....kkbbbbbbbbbbkkkk....',
      '....kkkkkkkkkkkkgyygk...',
      '...kgyygk......kgyggk...',
      '...kgyggk......kggggk...',
      '...kggggk......kooook...',
      '...kooook.......kkkk....',
      '....kkkk................',
      '........................',
    ],
  };

  S.node_puzzle = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      s: '#6e7a86',
      t: '#9aa7b3',
      u: '#cbd5de',
      r: '#8a6cf0',
      y: '#e2d8ff',
    },
    px: [
      '........................',
      '........................',
      '........................',
      '........kkkkkkkk........',
      '......kkuuuuuuuukk......',
      '.....kuuuttttttuuuk.....',
      '.....kuttttttttttuk.....',
      '.....kutrrrttrrrttk.....',
      '.....kutrtttttrtttk.....',
      '.....kutrryttryrttk.....',
      '.....kutrttttrttttk.....',
      '.....kuttttttttttsk.....',
      '.....kutrrrrrrrrtsk.....',
      '.....kuttttrrtttssk.....',
      '.....kutrrrryrrrtsk.....',
      '.....kutttttttttssk.....',
      '.....kutrytrtrrytsk.....',
      '.....kutrttrytrrtsk.....',
      '.....kuttttttttttsk.....',
      '.....kusssssssssssk.....',
      '.....kkkkkkkkkkkkkk.....',
      '........................',
      '........................',
      '........................',
    ],
  };

  S.node_start = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      y: '#dcb45c',
      o: '#a8802e',
      b: '#6b4a2f',
      c: '#9c7048',
      d: '#2a1a20',
      g: '#3f8a3a',
    },
    px: [
      '........................',
      '...........kk...........',
      '..........kyyk..........',
      '.........kyyyyk.........',
      '........kyyyyyok........',
      '.......kyyyyyyook.......',
      '......kyyyoyyyoook......',
      '.....kyyyyoyyyooook.....',
      '....kyyyoyyyoyyoooook...',
      '...kyyyyoyyyoyyooooook..',
      '..kyyyoyyyyooyyoooooook.',
      '.kkkkkkkkkkkkkkkkkkkkkk.',
      '..kooooooooooooooooook..',
      '....kccccckddkccccck....',
      '....kcbcbckddkcbcbck....',
      '....kccccckddkccccck....',
      '....kbcbcbkddkbcbcbk....',
      '....kccccckddkccccck....',
      '..gkcbcbckddkcbcbckg....',
      '.kgkccccckddkccccckgk...',
      '.kgkkkkkkkkkkkkkkkkgk...',
      '..kk..............kk....',
      '........................',
      '........................',
    ],
  };

  S.node_heart = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      r: '#c81e3a',
      p: '#f0506a',
      q: '#7a0e26',
      y: '#ffd0d8',
      g: '#ff8aa0',
      b: '#3a2028',
      c: '#6a4040',
    },
    px: [
      '........................',
      '....kkkkk......kkkkk....',
      '...kppprrk..g.krrrrrk...',
      '..kpyyprrrk..krrrrrrrk..',
      '..kpyyprrrrkkrrrrrrrqk..',
      '.kpppprrrrrrrrrrrrrrqqk.',
      '.kppprrrrrprrrrrrrrrqqk.',
      '.kpprrrrrrrrrrrprrrrqqk.',
      '.kprrrrprrrrrrrrrrrqqqk.',
      'g.krrrrrrrrrrrprrrrqqk..',
      '..krrrrrrrrrrrrrrrqqqk..',
      '...krrrrprrrrrrrrrqqk.g.',
      '....krrrrrrrrrrrrqqk....',
      '.....krrrrrrrrrrqqk.....',
      '......krrrrrrrrqqk......',
      '.......krrrbbrrqk.......',
      '........kkkbbkkk........',
      '..........kcbk..........',
      '..........kcbk..........',
      '.........kccbbk.........',
      '........kccbbbbk........',
      '.......kkkkkkkkkk.......',
      '........................',
      '........................',
    ],
  };

  S.node_mystery = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      d: '#3a1660',
      p: '#5a2a9a',
      l: '#e6d8ff',
      m: '#b48cff',
      y: '#ffffff',
    },
    px: [
      '........................',
      '...........kk...........',
      '.......kkkkddkkkk.......',
      '.....ykkpppppppdkk......',
      '.....kppdlllllldddk.....',
      '....kppdmllllllldddk....',
      '...kppdmllddddllldddk...',
      '..kkpddmllddddllldddkk..',
      '..kdpdddddddddlllddddk..',
      '..kydddddddddllldddddk..',
      '..kdddddddddlllddddddk..',
      '.kdddddddddlllddddddddk.',
      '.kddddddddmlldddddddddk.',
      '..kdddddddmllddddddddk..',
      '..kdddddddddddddddpddk..',
      '..kdddddddllldddddpydk..',
      '..kkddddddmmlddddppdkk..',
      '...kddddddddddddppddk...',
      '....kddddddddddppdyk....',
      '.....kddpppppppdddk.....',
      '......kkddddddddkk......',
      '.......kkkkddkkkk.......',
      '...........kk...........',
      '........................',
    ],
  };

  S.node_training = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      r: '#e0323c',
      w: '#f6f2ea',
      b: '#8a5a30',
      m: '#a9b4c2',
      f: '#f6e6ba',
    },
    px: [
      '.....................kk.',
      '...................kfffk',
      '.........kkkkkk...kffffk',
      '......kkkrrrrrrkkk.kkbk.',
      '.....kkrrrrrrrrrrkkkbk..',
      '....krrrrwwwwwwrrrkbk...',
      '...krrrwwwwwwwwwwkbkk...',
      '..kkrrwwwwrrrrwwkbkrkk..',
      '..krrwwwrrrrrrrkbkwrrk..',
      '..krrwwrrrwwwwkbkwwrrk..',
      '.krrwwwrrwwwwwbkrwwwrrk.',
      '.krrwwrrwwwkmmwwrrwwrrk.',
      '.krrwwrrwwrkmkwwrrwwrrk.',
      '.krrwwrrwwrkkrwwrrwwrrk.',
      '.krrwwrrwwwrrwwwrrwwrrk.',
      '.krrwwwrrwwwwwwrrwwwrrk.',
      '..krrwwrrrwwwwrrrwwrrk..',
      '..krrwwwrrrrrrrrwwwrrk..',
      '..kkrrwwwwrrrrwwwwrrkk..',
      '...krrrwwwwwwwwwwrrrk...',
      '....krrrrwwwwwwrrrrk....',
      '.....kkrrrrrrrrrrkk.....',
      '......kkkrrrrrrkkk......',
      '.........kkkkkk.........',
    ],
  };

  S.node_trap = {
    w: 24, h: 24,
    pal: {
      k: '#1b1023',
      m: '#8a96a4',
      l: '#d6dee6',
      d: '#4e5866',
      r: '#e0323c',
    },
    px: [
      '..........kkkk..........',
      '.......kkkkllkkkk.......',
      '.....kkllllllllllkk.....',
      '....kklllllkkllllmkk....',
      '...kklllmlmkkmlmmmmkk...',
      '..kkllkkklmkkmlkkkmmkk..',
      '..klllmkkmlkklmkkmlmmk..',
      '.klllllk.kk..kk.kllmmmk.',
      '.kllmmllk.kkkk.kllmmmmk.',
      'kkllkkkk.kddddk.kkkkmdkk',
      'dkllkkk.kddrrddk.kkkddkd',
      'dllllmmkkdrrrrdkkmmllddd',
      'dllllmmkkdrrrrdkkmmllddd',
      'dkllkkk.kddrrddk.kkkddkd',
      'kkllkkkk.kddddk.kkkkddkk',
      '.kllmmllk.kkkk.kllmmddk.',
      '.kllmllk.kk..kk.klldddk.',
      '..kmmlmkkmlkklmkkmlddk..',
      '..kkmmkkklmkkmlkkkddkk..',
      '...kkmmmmlmkkmlmdddkk...',
      '....kkmmmmdkkdddddkk....',
      '.....kkmmddddddddkk.....',
      '.......kkkkddkkkk.......',
      '..........kkkk..........',
    ],
  };

  S.node_locked = {
    w: 24, h: 24,
    pal: {
      k: '#2a2a3a',
      l: '#d4d4e0',
      g: '#9494a6',
      d: '#626274',
    },
    px: [
      '........................',
      '........................',
      '........................',
      '........................',
      '............kkkk........',
      '..........kkllllkk......',
      '.........kllllllllk.....',
      '....kkk..kllllllllgk....',
      '...klllkkllllllllgggk...',
      '..klllllllllllllgggggk..',
      '.kllllllllllllllggggggk.',
      '.kllllllllllllggggggggk.',
      '.klllllllllllgggggggggk.',
      'kllllllllllllggggggggggk',
      'kllllllllllgggggggggggdk',
      'klllllllllggggggggggdddk',
      '.kkllllggggggggggdddddk.',
      '...kkkddddddddddddkkk...',
      '......kkkkkkkkkkkk......',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  };

})();
