/* Deep Jungle — the spoils chest, shut and thrown open. */
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  // A banded chest, still closed.
  S.chest_shut = {
    w: 32, h: 32,
    pal: { k: '#170d05', d: '#3f2410', b: '#6b4020', l: '#9c6430', m: '#8a6a1c', h: '#e6c45a', g: '#ffe9a3', i: '#1d1006' },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...........kkkkkkkkkk...........',
      '.........kkllllllllllkk.........',
      '.......kkllllllllllllllkk.......',
      '......kmmllllllllllllllmmk......',
      '.....kbmmbbbbbbbbbbbbbbmmbk.....',
      '....kbbmmbbbbbbbbbbbbbbmmbbk....',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbhhhbbbbbbmmbbbk...',
      '...kbbbmmbbbbbhhhbbbbbbmmbbbk...',
      '...klllhhllllllllllllllhhlllk...',
      '...klllhhllllllllllllllhhlllk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...khhhhhhhhhhhhhhhhhhhhhhhhk...',
      '...kmmmmmmmmmmmmmmmmmmmmmmmmk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kdddmmddddddddddddddmmdddk...',
      '...kdddmmddddddddddddddmmdddk...',
      '....kkkkkkkkkkkkkkkkkkkkkkkk....',
      '................................',
      '................................',
      '................................',
    ],
  };

  // The same chest with its lid thrown back and the light out.
  S.chest_open = {
    w: 32, h: 32,
    pal: { k: '#170d05', d: '#3f2410', b: '#6b4020', l: '#9c6430', m: '#8a6a1c', h: '#e6c45a', g: '#ffe9a3', i: '#1d1006' },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '......kkkkkkkkkkkkkkkkkkkk......',
      '.....kddddmmddddddddmmddddk.....',
      '....kdddddmmddddddddmmdddddk....',
      '....kdddddmmddddddddmmdddddk....',
      '....kbbbbbmmbbbbbbbbmmbbbbbk....',
      '....kiiiiiiiiiiiiiiiiiiiiiik....',
      '....kiggggggggggggggggggggik....',
      '....kiggggggggggggggggggggik....',
      '....kiggggggggggggggggggggik....',
      '....khhhhhhhhhhhhhhhhhhhhhhk....',
      '...klllhhllllllllllllllhhlllk...',
      '...klllhhllllllllllllllhhlllk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...khhhhhhhhhhhhhhhhhhhhhhhhk...',
      '...kmmmmmmmmmmmmmmmmmmmmmmmmk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kbbbmmbbbbbbbbbbbbbbmmbbbk...',
      '...kdddmmddddddddddddddmmdddk...',
      '...kdddmmddddddddddddddmmdddk...',
      '....kkkkkkkkkkkkkkkkkkkkkkkk....',
      '................................',
      '................................',
      '................................',
    ],
  };

})();
