// js/sprites/ui_deco.js — extra jungle scenery props for the map background.
// Inert background dressing: strong silhouettes, lush greens, warm browns.
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  S.deco_palm = {
    w: 32, h: 48,
    pal: {
      b: '#7a5230',
      c: '#ab7c49',
      d: '#186024',
      g: '#2f9440',
      k: '#0d2010',
      l: '#6fd45c',
      n: '#4a3018',
      y: '#8a5a1c',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '.................kkkkkkkkk......',
      '................kkllkklllk......',
      '................klldkkkllk......',
      '............kkkkkkgdllgdgkkkkkk.',
      '............klllllldkkddlkllllk.',
      '............kkdddlkdlldglldlgkk.',
      '.............klgddlldkdllddglk..',
      '..........kkkkklkgdllgdgdgklkkkk',
      '........kkklgdddlgllgddglgldddgl',
      '.......kklldddgkldlldgdggdlkgddl',
      '.......klllklklgllldddddlllglklk',
      '.......kkkllldldlglldddllgldlglk',
      '........kkkdddkglklllnlllkggkddl',
      '.......kklddkglklklclllklklkkldd',
      '......kkllklkklkkycbnlycykkklkkd',
      '.....kklllklkkkkcyynkkyyyk.kkkkl',
      '.....kllklkkk..kyynnkkyynk....kk',
      '.....kllkkk....kkybcyykkkk......',
      '.....kkkk......kcnnyyyk.........',
      '..............kkcbnkynk.........',
      '..............kcbnkkkkk.........',
      '..............kcnnk.............',
      '.............kkcbnk.............',
      '.............kcbbnk.............',
      '............kkcnnkk.............',
      '............kcbbnk..............',
      '............kcbbnk..............',
      '...........kkcbnnk..............',
      '...........kcbbnkk..............',
      '...........kcbbnk...............',
      '...........kcbnnk...............',
      '...........kcbbnk...............',
      '..........kkcbbnk...............',
      '..........kcbbnnk...............',
      '..........kcbbbnk...............',
      '..........kcbbbnk...............',
      '..........kcbbnnk...............',
      '..........kcbbbnk...............',
      '..........kcbbbnk...............',
      '..........kcbbnnk...............',
      '.........kkcbbbnk...............',
      '........kkcbbbbnkk..............',
      '.......kkcbbbbbnnkk.............',
      '......kkcbbbbbbbbnkk............',
      '......kcbbbbbbbbbbnk............',
    ],
  };

  S.deco_bush = {
    w: 24, h: 16,
    pal: {
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
      s: '#0f3a18',
    },
    px: [
      '........................',
      '........................',
      '........kkkkkkkk........',
      '.......kkgggggdkk.......',
      '...kkkkkgllllggdkkkkk...',
      '.kkkdddgllllslggdkddkkk.',
      'kkdllggglllllsgggllggdkk',
      'kdglllsggllllgggllslggdk',
      'kgglllgsgggggggglllsggdk',
      'kgggggggggggggggggggggdd',
      'kggggglllsgggllsgggggggd',
      'dgggsgggggsgggggsggggsgg',
      'dggggsgggggdgggggggdggsg',
      'ddsddggggggdsgggggddgggd',
      'kddsdddddddddsdddddkdddd',
      'kkkkkkdddddkkdddddkkkkkk',
    ],
  };

  S.deco_log = {
    w: 32, h: 16,
    pal: {
      b: '#7a5230',
      c: '#ab7c49',
      d: '#17501f',
      g: '#2f9440',
      k: '#180f08',
      l: '#6fd45c',
      n: '#4a3018',
    },
    px: [
      '................................',
      '....................kkk.........',
      '.............kkk...kkgk.kkk.....',
      '..kkkk......kkgkkkkklgkkkgk.....',
      '.kknnkkkkkkkklgdddddkkkklgk.....',
      'kkcccckcddddddddddddddddddkkkk..',
      'kncnncncdddddddddddddddddddddkk.',
      'kcnnnncbbbdddddbbbbddddbbdddddkk',
      'kcnccncbbbnnnnnnnbbbbbnnnnnnbbbk',
      'kcnccncbbbbbbbbbbbbbbbbbbbbbbbbk',
      'kcnnnncbbbbbbbbbbbbnnnnnnbbbbbkk',
      'kncnncnnnnnnnnnnnnnnnnnnnnnnnkk.',
      'kkccccknnnnnnnnnnnnnnnnnnnkkkk..',
      '.kknnkkkkkkkknnnnnnnkkkkkkk.....',
      '..kkkk......kkkkkkkkk...........',
      '................................',
    ],
  };

  S.deco_stump = {
    w: 24, h: 16,
    pal: {
      b: '#7a5230',
      c: '#ab7c49',
      d: '#17501f',
      g: '#2f9440',
      k: '#180f08',
      l: '#6fd45c',
      n: '#4a3018',
      r: '#8a6136',
      w: '#cfa06a',
    },
    px: [
      '........................',
      '.......kkkkkkkkkkk......',
      '....kkkkrrrrrrrrrkkkk...',
      '...kkrrwwwwrrrwwwwrrkk..',
      '...krrwwrrrwrrrrrwwrrk..',
      '...kddddrrwwwwwrrrrrrk..',
      '..kkdddddwrrrrrwwwwrnkk.',
      '..kddddddrwwwwwrrrddddk.',
      '..kdddddbnbbnbbnbdddddk.',
      '.kkccbnbbnbbnbbnbdddddkk',
      '.kccbnbbnbbnbbnbbndddddk',
      'kklcbnbbnbbnbbnbbnbbnlnk',
      'kcgbnbbnbbnbbnbbnbbnbgnn',
      'kccbnddddddddnbbdddddbnn',
      'ccbdddddddddlddddddddddn',
      'cbndddddddddgddddddddddn',
    ],
  };

  S.deco_boulder = {
    w: 32, h: 24,
    pal: {
      d: '#17501f',
      e: '#6fd45c',
      g: '#2f9440',
      k: '#12161e',
      l: '#98a2b0',
      m: '#666e7c',
      s: '#3c4450',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '.......kkkkkkkkkkk..............',
      '.....kkkeeeeeessskkk..kkk.......',
      '....kkeegdggdgmmmsekkkkekkkkk...',
      '...kkedggldgldmmmmdeeeegeeeskk..',
      '...keglddlldlssmmmmggdggdggsskk.',
      '...kggmllllllmsmmmldglddmdgmsskk',
      '...kddmmmmmmmmsmmmmldlllmmdmmsek',
      '...ksmmmlllllllslllmmmmmmmmmmsdk',
      '..kksmlllllllllsllllllmmmmmmmssk',
      '..kellllllllllllsllllllmmmmmsssk',
      '.kkdllllllllllllsllllllmmmmmsssk',
      '.kemlsssslllllllsssllllmmmmmsskk',
      '.kgmmlllssssllllslssssmmmmmmssk.',
      '.kgmmmmllllllllsslllmssssmmmssk.',
      '.kdmmmmmmmmmmmmsmmmmmmmmddsmssk.',
      '.kssdddddmmmmmssmmmmmmddddddssk.',
      '.kkdddddddmmmmsmmmmmmddddddddkk.',
      '..kdddddddmmmssmmmmmmmddddddsk..',
      '..kkdddddmmmmsmmmmmmmmssddsskk..',
      '...kkksssssssssssssssssssskkk...',
      '.....kkksssssssssssssssskkk.....',
    ],
  };

  S.deco_lilypad = {
    w: 24, h: 16,
    pal: {
      d: '#17501f',
      g: '#2f9440',
      k: '#08181e',
      l: '#6fd45c',
      m: '#c02870',
      p: '#f070b0',
      v: '#256272',
      w: '#164250',
      y: '#ffd84a',
    },
    px: [
      '........kkkk............',
      '.......kkpmkk...........',
      '......kkppppkk..........',
      '......kmpyypmkkkkkkk....',
      '..kkkkkkpyypkkkkkkkkkk..',
      '..kvvvvvmppmddgggddkkkk.',
      '.kkwwwwwwkkllldlddlgkkkk',
      'kkwwwwwwwkdddddkkddddkwk',
      'kwkkkkkkkkdglllkkkkgdkww',
      'kkkddllddkkdggggkkkkkkww',
      'kkddddddddkkddddddkwwwww',
      'kdgdkkkddgdkkkkkkkkkkkkk',
      'kkdkkkkggdkkwwwkklldddgk',
      'kkkkkddddkkwwwwkddddkkdd',
      'kkwkkkkkkkvvwwwkkddgkkkk',
      '.kkkkkkkwwwwwwwwkkkkkkwk',
    ],
  };

  S.deco_reeds = {
    w: 16, h: 24,
    pal: {
      b: '#2a4a18',
      c: '#9a6a30',
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
      n: '#5a3a18',
    },
    px: [
      '..kgk......kkk..',
      '.kknk......kgk..',
      '.kcckk....kkgk..',
      '.kccnk....kllk..',
      '.kccnk.kkkkcnk..',
      '.kccnk.kgkkcnk..',
      '.knnnk.kgkkcnk..',
      '.kknkk.kgkkcnk..',
      'kkkllk.kgkkcnk..',
      'kgkklk.kgkknnkkk',
      'kgkklkkkgkklkkkg',
      'kgkklkkggkklkkkg',
      'kgkkgkkgkkglkkgg',
      'kgkkgkkgkkgkkkgk',
      'kgkkgkkdkkgk.kgk',
      'kgkkgkkdkkgkkkgk',
      'kdkkgkkdkkgkdkgk',
      'kdkkgkkdkkgdkddk',
      'kddkgkkdkkddkdkd',
      'kdddgkkdkkddkddk',
      'kddddkkdkddkkddk',
      'kdddddkdkddkkddk',
      'kbbbbbbdkdgkkdkk',
      'kdkbbbbbbbbbbbbk',
    ],
  };

  S.deco_orchid = {
    w: 16, h: 24,
    pal: {
      d: '#17501f',
      g: '#2f9440',
      k: '#280a1e',
      m: '#8a1060',
      p: '#e04aa8',
      w: '#ffb0e0',
      y: '#ffd84a',
    },
    px: [
      '......kkk.......',
      '......kmkk......',
      '.....kkpmk......',
      '..kkkkmwpkkkkk..',
      '..kmmpmwwpppmk..',
      '..kmpwwyywwpkk..',
      '..kkmmyyyymmk...',
      '...kmppmyppmk...',
      '...kmppmmppmk...',
      '...kmmmwwmmmk...',
      '...kkkmwwmkkk...',
      '.....kkmmdk.....',
      '......kkgdk.....',
      '.......kgdk.....',
      '.......kgdkk....',
      '.......kkgdk....',
      '.kkk....kgdk....',
      '.kdkkkk.kgdkkkkk',
      '.kdggdkkkgdkkddk',
      '.kkdgggkkgdgggdk',
      '..kddgggkgdggdkk',
      '..kkddggkgdgdkk.',
      '...kkkddggddkk..',
      '.....kkkkgdkk...',
    ],
  };

  S.deco_bones = {
    w: 24, h: 16,
    pal: {
      c: '#cfc2a4',
      k: '#221a14',
      n: '#9a8a6c',
      s: '#6a5c44',
      w: '#f2ead6',
    },
    px: [
      '........................',
      '........................',
      '........................',
      '...kkkkkkkk.........kkk.',
      '..kkwwwwcckk.......kkckk',
      '..kwwwwwwcckkkkkkkkkccck',
      '..kwwwwwwcckcckknnnnnnck',
      '..kwkswwksckcnnnnccwwwwk',
      '..kwkkwwkkckcwwwwwwwkwcc',
      '..kccwcnccckcwckkkkkkkck',
      '..kkwwwkcckkkcckwwwckkck',
      '...kwwwwwckkkckkcccckccc',
      '...kwwwwcckkccnnnnnnnnnc',
      '..kkkwkwkwkkknncccwwwwwc',
      '..kskkcckkskkcwwwwkkkcwc',
      '..kkkkkkkkkknnnnnnk.kkck',
    ],
  };

  S.deco_ruin = {
    w: 32, h: 32,
    pal: {
      d: '#17501f',
      e: '#6fd45c',
      g: '#2f9440',
      k: '#141820',
      l: '#8a92a0',
      m: '#5e6470',
      s: '#3c4048',
      y: '#c8a840',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '................kkkk............',
      '.............kkkkggk............',
      '...........kkklggekk............',
      '...........klllgdgk.............',
      '........kkkkllgdllk.............',
      '........kggkmgdmllk.............',
      '........kgegggdmmmk.............',
      '........klgggdsmmmkkk...........',
      '........kllgdmsmmmllk...........',
      '........kllgdggmmmllk...........',
      '.......kkllgdesmmmsmkkkkk.......',
      '.......kllggglllllllllllk.......',
      '.......kmmmgdmmmmmmmmmmmkk......',
      '.......kgeggdymyymyymyyeek......',
      '.......kmgggdsmysmysmyeeek......',
      '.......ksssgdsssssssssgskkkk....',
      '.......ksssgdsggssssssgskeek....',
      '.......kkllgdgemmmsmmssgeeek....',
      '........kllmgdgmmmsmmssgekkkkkkk',
      '.......kkllmgdsmmmsmmsskglllllsk',
      '.......kgglmgdsmmmsmmsskmgmeeesk',
      '.......kgeggdmsmmmsmmsskmmgeemsk',
      '.......kkgggdmsmmmsmmsskmmggmmsk',
      '..kkkkkkklggdmsmmmsmmssksssgsesk',
      '..kllllllggdmmmmmmmmmmmllllgeekk',
      '..kmmmmmmgdgmmmmmmmmmmmmmmmeeek.',
      '..ksssssggsssssssssssssssssgskk.',
      '..kssssgdssssssssssssssssssgsk..',
      '..kkkkkgdkkkkkkkkkkkkkkkkkkkkk..',
    ],
  };

  S.deco_campfire = {
    w: 24, h: 16,
    pal: {
      b: '#7a5230',
      k: '#181008',
      m: '#7a828e',
      n: '#4a3018',
      o: '#f0791a',
      r: '#c22a10',
      s: '#41474f',
      y: '#ffd24a',
    },
    px: [
      '..........kkk...........',
      '.........kkrk...........',
      '........kkrrkk..........',
      '........krrork..........',
      '........kroorkk.........',
      '.......kkroorrkk........',
      '.......krrooorrk........',
      '.....kkkrooooorkkk......',
      '.....kbbnooyyornbkk.....',
      '.....kbbbbbbbbbbbnk.....',
      '....kknnnnbbbbbnnkkk....',
      '.kkkknbbbbnnnbbbbbnkkkkk',
      'kkssbbbbnnnyynnnbbbbmmss',
      'smmmsnmmskrmmskkmmsnmmms',
      'smmssmmmmsmmmmsmmmmssmss',
      'ssssssmmssmmmmssmmssssss',
    ],
  };

  S.deco_mushroom_cluster = {
    w: 24, h: 16,
    pal: {
      c: '#f0e0c0',
      d: '#17501f',
      k: '#241010',
      q: '#8a1a24',
      r: '#d43038',
      s: '#b8a684',
      t: '#d6a45c',
      u: '#8f6330',
      w: '#fff0e0',
    },
    px: [
      '........................',
      '....kkkkk...............',
      '..kkkrrrkkk.............',
      '.kkrrrrrrrkk............',
      '.krrwrrwwrrk............',
      '.krrwrrrrrrkkkkkkk......',
      '.kqrrwwrwwqkkttttkk.....',
      'kkqqrrrrrqqkttttttkk....',
      'kqqqqqqqqqqutwttwtukkkk.',
      'kkkkkccskkkuttttwturrrkk',
      'ktttkccskkkkuuuuuqrwrrrk',
      'utwwuccskkuuuuuuuqrwrwrq',
      'utttuccskkkkkccskqqrrwqk',
      'uuuuuccsk...kccsqqqqqqqq',
      'kccskccskkkkkccskkccskkk',
      'ddcddcddkddkddcddkddsddk',
    ],
  };

  S.deco_hangvine = {
    w: 16, h: 40,
    pal: {
      b: '#2a4a18',
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
      p: '#e858a0',
    },
    px: [
      'kkgggdkkkkgggdkk',
      'kggggggggggggggk',
      'dgggllllllgggggd',
      'ddgggggggggggddd',
      'kggggggggggggggk',
      'dggggggggggdgggd',
      'ddgddggggggdggdd',
      'kdddddggggdddddd',
      'kkkkkddddddlgdkk',
      '....kkkkbddgdkk.',
      '..kkkkkkbdddkkk.',
      '..kdddkkbddkkk..',
      '..kkglgdbddkk...',
      '..kkdgggbddkk...',
      '..kkkdddbddkkkk.',
      '...kkkkkbdklpdk.',
      '....kkkkbdkppdk.',
      '.......kbdggdkk.',
      '....kkkkbdddkkk.',
      '...kkgdkkbdkkk..',
      '...kkdlgdbdkk...',
      '...kkdgggbdk....',
      '....kkkdgbdkkkk.',
      '....kkkkkbdkddk.',
      '......kkkbdlgkk.',
      '........kbdgdkk.',
      '.....kkkkbddkkk.',
      '....kkgkkbdkkk..',
      '....kkdldbdk....',
      '....kkkggbdk....',
      '.....kkkdbkkkk..',
      '.....kkkkbkkgk..',
      '........kbdldk..',
      '........kbggkk..',
      '.....kkkkbdkkk..',
      '.....kdkkbkkkk..',
      '.....kkglbk.....',
      '.....kkdgbk.....',
      '.....kkkkbk.....',
      '......kkkbk.....',
    ],
  };

  S.deco_fern_big = {
    w: 32, h: 24,
    pal: {
      b: '#2a4a18',
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...............kkk..............',
      '...........kkk.klk.kkk..........',
      '......kkk..klkkklkkklk..kkk.....',
      '......kgkkkklllllllllkkkkgk.....',
      '......kgggklllkdbdklllkgggk.....',
      '......kggggkgbllblgbgkggggk.....',
      '.....kkkgbbdlbblbgbbldbbgkkk....',
      '..kkkklkgkbbdglklkbgdbbkgklkkkk.',
      '..klllbblglblklllgbklblglbblllk.',
      '..kklggbbbggbllblbglbggbbbgglkk.',
      '.kkkkklklkgbllllgbgllbgklklkkkkk',
      'kkgdgdgdlldggggdbbglggdlldgdgdgk',
      'ggggbbbbblbgllbdddbllgblbbbbbggg',
      'kgkgkgkgkdklgbdddddbglkdkgkgkgkg',
      'kkkkkgkgkgkgdddddddddgkgkgkgkkkk',
      '....kkkkkkkbbbbbbbbbbbkkkkkkk...',
    ],
  };

})();