// js/sprites/ui_deco.js — extra jungle scenery props for the map background.
// Inert background dressing: strong silhouettes, lush greens, warm browns.
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  S.deco_palm = {
    w: 32, h: 48,
    pal: {
      b: '#7a5230',
      c: '#ab7c49',
      d: '#186024',
      g: '#2f9440',
      k: '#0d2010',
      l: '#6fd45c',
      n: '#4a3018',
      y: '#8a5a1c',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '...............kkkkkkkkk........',
      '...........kkkkkldlkldlkkkkk....',
      '..........kkdlkkldllldlkkldkk...',
      '..........kldddllddlddlldddlk...',
      '..........kklgddlllldllddglkk...',
      '........kkkkklgdlglgdgldglkkkkk.',
      '......kkkllllllglllgdllgllllllkk',
      '......kdddddddllllgddglllddddddd',
      '......klllllgggllldddlllggglllll',
      '......kkklllllllldddddllllllllkk',
      '.....kkkldddgglllldddllllggdddlk',
      '....kkldddlllllllllglllllllllddd',
      '....kgddlllklkyyylllllyykklkllld',
      '....kdllkkkkkkyynbbnkyyyykkkkkkl',
      '....kkkkk....kkkcbnnkkynkk....kk',
      '..............kkcbnkkkkkk.......',
      '..............kcbbnk............',
      '..............kcbnnk............',
      '.............kkcbbnk............',
      '.............kcbbnkk............',
      '.............kcbnnk.............',
      '............kkcbbnk.............',
      '............kcbbbnk.............',
      '............kcbbnnk.............',
      '...........kkcbbnkk.............',
      '...........kcbbbnk..............',
      '...........kcbbnnk..............',
      '...........kcbbbnk..............',
      '...........kcbbbnk..............',
      '..........kkcbbnnk..............',
      '..........kcbbbbnk..............',
      '..........kcbbbbnk..............',
      '..........kcbbbnnk..............',
      '..........kcbbbbnk..............',
      '..........kcbbbbnk..............',
      '..........kcbbbnnk..............',
      '..........kcbbbbnk..............',
      '.........kkcbbbbnk..............',
      '.........kcbbbbnnk..............',
      '........kkcbbbbbnkk.............',
      '........kcbbbbbbbnkk............',
      '.......kkcbbbbbbbnnk............',
      '......kkcbbbbbbbbbnkk...........',
      '......kcbbbbbbbbbbbnk...........',
    ],
  };

  S.deco_bush = {
    w: 24, h: 16,
    pal: {
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
      s: '#0f3a18',
    },
    px: [
      '........................',
      '........................',
      '........kkkkkkkk........',
      '.......kkgggggdkk.......',
      '...kkkkkgllllggdkkkkk...',
      '.kkkdddgllllslggdkddkkk.',
      'kkdllggglllllsgggllggdkk',
      'kdglllsggllllgggllslggdk',
      'kgglllgsgggggggglllsggdk',
      'kgggggggggggggggggggggdd',
      'kggggglllsgggllsgggggggd',
      'dgggsgggggsgggggsggggsgg',
      'dggggsgggggdgggggggdggsg',
      'ddsddggggggdsgggggddgggd',
      'kddsdddddddddsdddddkdddd',
      'kkkkkkdddddkkdddddkkkkkk',
    ],
  };

  S.deco_log = {
    w: 32, h: 16,
    pal: {
      b: '#7a5230',
      c: '#ab7c49',
      d: '#17501f',
      n: '#4a3018',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...nn.......ddddddddd...........',
      '..cccccccdddddddddddddddddd.....',
      '.ncnncnbbbdddddbbbbdddbbbdddd...',
      '.cnccncbbbnnnnnnbbbbbbbbbbbbbbb.',
      '.cnccncbbbbbbbbbbbbbbbbbbbbbbbb.',
      '.cnccncbbbbbbbbbbbbnnnnnbbbbbbb.',
      '.ncnncnnnnnnnnnnnnnnnnnnnnnnn...',
      '..ccccnnnnnnnnnnnnnnnnnnnnn.....',
      '...nn.......nnnnnnnnn...........',
      '................................',
      '................................',
    ],
  };

  S.deco_stump = {
    w: 24, h: 16,
    pal: {
      b: '#7a5230',
      c: '#ab7c49',
      d: '#17501f',
      k: '#180f08',
      n: '#4a3018',
      r: '#8a6136',
      w: '#cfa06a',
    },
    px: [
      '........................',
      '.......kkkkkkkkkkk......',
      '....kkkkrrrrrrrrrkkkk...',
      '...kkrrwwwwrrrwwwwrrkk..',
      '...krrwwrrrwrrrrrwwrrk..',
      '...krwwwrrwwwwwrrrrrrk..',
      '..kkdddwwwrrrrrwwwwrnkk.',
      '..kdddddrrwwwwwrrrnbnnk.',
      '..kdddddbnbbnbbnbbddddk.',
      '.kkddddbbnbbnbbnbdddddkk',
      '.kccbnbbnbbnbbnbbddddddk',
      'kkccbnbbnbbnbbnbbnddddnk',
      'kccbnbbnbbnbbnbbnbbnbbnn',
      'kccbnbbndddddddbnbbnbbnn',
      'ccbnbbndddddddddbbnbbnbn',
      'cbnbbnbdddddddddbnbbnbbn',
    ],
  };

  S.deco_boulder = {
    w: 32, h: 24,
    pal: {
      d: '#17501f',
      k: '#12161e',
      l: '#98a2b0',
      m: '#666e7c',
      s: '#3c4450',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '..........kkk...................',
      '......kkkkkskkkkk...............',
      '....kkkddddddsddkkkkkkkkkkk.....',
      '...kkdddddddddddddkdddddddkkk...',
      '..kkddddddddddddddddddddddsskk..',
      '..ksmddddddddmdddddddddddmmsskk.',
      '..ksmmmmddllllslldddddlmmmmddsk.',
      '..ksmllllllllllslllllmmmmdddddk.',
      '.kkdddlllllllllslllllllmmdddddk.',
      'kkdddddllllllllslllllllmmdddddk.',
      'ksddddllllllllllsllllllmmmmddsk.',
      'ksmmllllllllllllsslllllmmmmmssk.',
      'ksmmmmlllllllllsslsssmmmmmmmssk.',
      'ksmmmmmmmmlllllslmmmmsssmmmmssk.',
      'kssmmmmmmmmmmmssmmmmmmmmssmsssk.',
      'kkssmmmmmmmmmmsmmmmmmmmmmmssskk.',
      '.kksssmmmmmmmssmmmmmmmmmsssskk..',
      '..kkssssmmmmmsmmmmmmmmssssskk...',
      '...kkkssssssssssssssssssskkk....',
      '.....kkkssssssssssssssskkk......',
      '.......kkkkkssssssskkkkk........',
    ],
  };

  S.deco_lilypad = {
    w: 24, h: 16,
    pal: {
      d: '#17501f',
      g: '#2f9440',
      k: '#08181e',
      l: '#6fd45c',
      p: '#e858a0',
      v: '#256272',
      w: '#164250',
      y: '#ffd84a',
    },
    px: [
      '........................',
      '........................',
      '........................',
      '.............kkkkkk.....',
      '........kkkkkkppppk.....',
      '....kkkkkwwwwwppypkkk...',
      '..kkkwwwwwkkkkppppkkkkk.',
      '.kkwvvvvvkkddggggddkkwkk',
      'kkwkkkkkkkdlllllllgdkwwk',
      'kwkkdggggdgggggkggggkwww',
      'kwkgglllggdggggkkkgdkwww',
      'kwkdgkkkggdddddddkkkkkww',
      'kkkkkkddddkkkkkkkddddkkk',
      '.kkwwkkkkkkwwwwkggggggkk',
      '..kkkwvvvvvvwwwkdggkkdk.',
      '....kkkkkwwwwwwkkdddkkk.',
    ],
  };

  S.deco_reeds = {
    w: 16, h: 24,
    pal: {
      b: '#2a4a18',
      c: '#8f6330',
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
      n: '#5a3a18',
    },
    px: [
      '.....kkk........',
      '.....klk........',
      '.....klkkk......',
      '.....klklk......',
      '.....klklkk.....',
      '.kkk.klklckk....',
      'kklk.klklnck....',
      'knck.klkllckkkk.',
      'knckkkdknlckklk.',
      'knckkdkkcdckklk.',
      'knckkdkkkdkkklk.',
      'kcckkdkkgddkklk.',
      'kkgkkdkkgkdkklkk',
      '.kgkkdkkgkdkkggk',
      '.kgkkdkkgkdkkkgk',
      '.kgkkdkkgkdk.kgk',
      '.kgkkdkkgkdkkkgk',
      '.kgkkdkkgkddkkgk',
      '.kgkkdkkgkkdkkgk',
      '.kgkkdkkgkkdkkgk',
      '.kgkkdkkgkkdkkgk',
      'kkgkkdkkgkkdkkgk',
      'kbbbbbkkgkkdkkgk',
      'kkgbbbbbbbbbbbgk',
    ],
  };

  S.deco_orchid = {
    w: 16, h: 24,
    pal: {
      d: '#17501f',
      g: '#2f9440',
      k: '#280a1e',
      m: '#8a1060',
      p: '#d8309a',
      w: '#ff9fd8',
      y: '#ffd84a',
    },
    px: [
      '................',
      '......kkkk......',
      '...kkkkppkkkk...',
      '...kpppwwpppk...',
      '...kpwwwwwwpk...',
      '...kpwwyywwpk...',
      '..kkpwyyyywpkk..',
      '..kppwwymwwppk..',
      '..kppppmmppppk..',
      '..kkkkmmmmkkkk..',
      '.....kkmmdk.....',
      '......kkgdk.....',
      '.......kgdk.....',
      '.......kgdk.....',
      '.......kgdk.....',
      '.......kgdkk....',
      '.......kkgdk....',
      '.kkkkk..kgdk....',
      '.kdggkkkkgdkkkk.',
      '.kkdggdkkgddggk.',
      '..kddggdkgdggdk.',
      '..kkddggkgdgdkk.',
      '...kkkddggddkk..',
      '.....kkkkgdkk...',
    ],
  };

  S.deco_bones = {
    w: 24, h: 16,
    pal: {
      c: '#cfc2a4',
      k: '#221a14',
      n: '#9a8a6c',
      s: '#6a5c44',
      w: '#f2ead6',
    },
    px: [
      '........................',
      '........................',
      '........................',
      '...kkkkkkkk.............',
      '..kkwwwwcckk............',
      '..kwwwwwwcck............',
      '..kwwwwwwcckkkkk....kkkk',
      '..kwkkwwkkckccck...kkcck',
      '..kwkkwwkkckcnnkkkkknncc',
      '..kccwcnccccwwcnnkknncwc',
      '..kkwwwkcckccwwcnnncwwcc',
      '...kwwwwwckkkkkwwcnnnkkk',
      '...kwwwwcckccnnnwwwcnncc',
      '..kkkwkwkwkcnncwwkwwwcnn',
      '..kskkcckksccwwkkkkkwwcc',
      '..kkkkkkkkkkcwck...kccwk',
    ],
  };

  S.deco_ruin = {
    w: 32, h: 32,
    pal: {
      d: '#17501f',
      e: '#6fd45c',
      g: '#2f9440',
      k: '#141820',
      l: '#8a92a0',
      m: '#5e6470',
      s: '#3c4048',
      y: '#c8a840',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '..............kkk...............',
      '..........kkkkklkk..............',
      '..........kggllmlk..............',
      '..........kgegggdkk.............',
      '..........klmggdmlk.............',
      '.........kkmmgdmmmkk............',
      '........kklmgdsmmmlk............',
      '........kllmgdgmmmskk...........',
      '........kllgggsmmmslkk..........',
      '.......kkllgdmsmmmsmlkkkk.......',
      '.......klllgdlllllllllllk.......',
      '.......kgeggdymmymmymmymk.......',
      '.......kmgggdysmysmysmymk.......',
      '.......kmmmgdmmmmmmmmmmmk.......',
      '.......ksssgdsssssssssgskkk.....',
      '.......kkllgdgemmmsmmsgkeek.....',
      '........kllgdggmmmsmmsggeek.....',
      '........kllmgdsmmmsmmssgkkkkkkkk',
      '.......kkllmgdsmmmsmmsskgllllllk',
      '.......kggggdmsmmmsmmsskggeeemmk',
      '.......kkeggdmsmmmsmmsskmgeemmmk',
      '........kllgdmsmmmsmmsskmmgmmmmk',
      '..kkkkkkklgdmmsmmmsmmsskssgssssk',
      '..kllllllggdmmmmmmmmmmmlllgeeekk',
      '..kmmmmmmgdgmmmmmmmmmmmmmmgeekk.',
      '..ksssssggssssssssssssssssgssk..',
      '..kssssgdsssssssssssssssssgssk..',
      '..kkkkkgdkkkkkkkkkkkkkkkkkkkkk..',
    ],
  };

  S.deco_campfire = {
    w: 24, h: 16,
    pal: {
      b: '#7a5230',
      k: '#181008',
      m: '#7a828e',
      n: '#4a3018',
      o: '#f0791a',
      r: '#c22a10',
      s: '#41474f',
      y: '#ffd24a',
    },
    px: [
      '..........kkk...........',
      '.........kkrk...........',
      '........kkrrkk..........',
      '........krrork..........',
      '........kroorkk.........',
      '.......kkroorrkk........',
      '.......krrooorrk........',
      '.......krroooork........',
      '......kkrooyyorkk.......',
      '......kbbboyybbbk.......',
      '.....kknnbbbbbbbkk..kkk.',
      'kkkkkkbbbnnnnbbbbkkkkskk',
      'kmmmsbbsbbbyynnnbsbsmmss',
      'kmmmsmmmmssmmmsmmmmsmmms',
      'ksmsssmmmsmmmmssmmmsssss',
      'kssssssssssmmssssssssssk',
    ],
  };

  S.deco_mushroom_cluster = {
    w: 24, h: 16,
    pal: {
      c: '#f0e0c0',
      d: '#17501f',
      k: '#241010',
      q: '#8a1a24',
      r: '#d43038',
      s: '#b8a684',
      t: '#d6a45c',
      u: '#8f6330',
      w: '#fff0e0',
    },
    px: [
      '........................',
      '....kkkkk...............',
      '..kkkrrrkkk.............',
      '.kkrrrrrrrkk............',
      '.krrwrrwwrrk............',
      '.krrwrrrrrrkkkkkkk......',
      '.kqrrwwrwwqkkttttkk.....',
      'kkqqrrrrrqqkttttttkk....',
      'kqqqqqqqqqqutwttwtukkkk.',
      'kkkkkccskkkuttttwturrrkk',
      'ktttkccskkkkuuuuuqrwrrrk',
      'utwwuccskkuuuuuuuqrwrwrq',
      'utttuccskkkkkccskqqrrwqk',
      'uuuuuccsk...kccsqqqqqqqq',
      'kccskccskkkkkccskkccskkk',
      'ddcddcddkddkddcddkddsddk',
    ],
  };

  S.deco_hangvine = {
    w: 16, h: 40,
    pal: {
      b: '#2a4a18',
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
      p: '#e858a0',
    },
    px: [
      'kkggggdkkggggdkk',
      'kggggggdgggggggk',
      'dgggggggggggggdd',
      'kddgllllllgggddk',
      'kdggggggggbbggdk',
      'dgggggggggbbgggd',
      'ddgddgggggbbggdd',
      'kddddddddgbbdddk',
      'kkkkkkkkkkgdglgk',
      '.........kggggdk',
      '.........kggddkk',
      '.........kgbbkk.',
      '.....kkkkkgllpk.',
      '.....klgdkgpppk.',
      '.....kdggggbkkk.',
      '.....kkdgggbk...',
      '......kkkkgbk...',
      '........kgbkkk..',
      '........kgdldk..',
      '........kgggdk..',
      '.......kkgddkk..',
      '.......kgbkkk...',
      '...kkkkkgbk.....',
      '...kdldkgbk.....',
      '...kdgggbkk.....',
      '...kkddgbk......',
      '....kkkgkk......',
      '.....kgkkkk.....',
      '.....kgdldk.....',
      '.....kggdkk.....',
      '....kkgdkk......',
      '....kgkkk.......',
      '..kkkgk.........',
      '..kglgk.........',
      '..kdggk.........',
      '..kkdgk.........',
      '...kkgk.........',
      '....kgk.........',
      '....kgk.........',
      '....kgk.........',
    ],
  };

  S.deco_fern_big = {
    w: 32, h: 24,
    pal: {
      b: '#2a4a18',
      d: '#17501f',
      g: '#2f9440',
      k: '#0b2411',
      l: '#6fd45c',
    },
    px: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..............kkkkk.............',
      '..........kkkkkgbgkkkkk.........',
      '..........kgblkgbgklbgk.........',
      '......kkk.klbllgbgllblk.kkk.....',
      '.....kkgkkklbblgbglbblkkkgkk....',
      '.....kdbbggklbggbllblkggbbdk....',
      '.....kggbbbglbgdllbblgbbbggk....',
      '.....kkggdbblggdlgbglbbdggkk....',
      '..kkkklllggbllgllbbllbgglllkkkk.',
      '..kbbbbbblggllllgbgllgglbbbbbbk.',
      '..kllggggbbglgllgbgllgbbggggllk.',
      '..kkkllllllgglbbbbblggllllllkkk.',
      '...kggbbblllglbbbbblglllbbbggk..',
    ],
  };

})();