// js/sprites/ui_items.js — 16x16 item + potion icons.
// Text pixel grids; see docs/ART_SPEC.md. Plain script (not a module).
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  // ---------------------------------------------------------------- weapons

  S.item_sword = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#eef4f8',
      s: '#a9b4c2',
      g: '#f6c94a',
      h: '#7a4e28',
    },
    px: [
      '.......kk.......',
      '......kwsk......',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '..kkkkwwsskkkk..',
      '..kgggwwssgggk..',
      '..kkkkwwsskkkk..',
      '......khhk......',
      '......khhk......',
      '.....kgggk......',
      '.....kkkkk......',
    ],
  };

  S.item_dagger = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#eef4f8',
      s: '#a9b4c2',
      g: '#c8a24a',
      h: '#6b3a2a',
    },
    px: [
      '................',
      '................',
      '................',
      '.......kk.......',
      '......kwsk......',
      '.....kwwssk.....',
      '.....kwwssk.....',
      '......kwsk......',
      '......kwsk......',
      '....kkkwskkk....',
      '....kggwsggk....',
      '....kkkwskkk....',
      '......khhk......',
      '......khhk......',
      '.....kgggk......',
      '.....kkkkk......',
    ],
  };

  S.item_axe = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#dbe4ec',
      s: '#8a96a4',
      c: '#b07a44',
      h: '#7a4e28',
    },
    px: [
      '.........kchk...',
      '.........kchk...',
      '.....kkkkkchk...',
      '...kkwwwskchk...',
      '..kwwwwwskchk...',
      '.kwwwwwwskchk...',
      '.kwwwwwwskchk...',
      '.kwwwwwwskchk...',
      '.kwwwwwsskchk...',
      '..kwwwwsskchk...',
      '...kwwwsskchk...',
      '.....kkkkkchk...',
      '.........kchk...',
      '.........kchk...',
      '.........kchk...',
      '.........kkkk...',
    ],
  };

  S.item_spear = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#eef4f8',
      s: '#a9b4c2',
      g: '#f6c94a',
      c: '#b07a44',
      h: '#7a4e28',
    },
    px: [
      '.......kk.......',
      '......kwsk......',
      '.....kwwssk.....',
      '....kwwwsssk....',
      '...kwwwwssssk...',
      '...kwwwwssssk...',
      '....kwwwsssk....',
      '.....kwwssk.....',
      '.....kggggk.....',
      '.....kggggk.....',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kkkk......',
    ],
  };

  S.item_mace = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      m: '#8a96a4',
      w: '#d6dee6',
      c: '#b07a44',
      h: '#7a4e28',
      g: '#f6c94a',
    },
    px: [
      '...k..kkkk..k...',
      '...kk.kmmk.kk...',
      '..kkmkkmmkkmkk..',
      '.kkmmmmmmmmmmkk.',
      'kmmmmwwwwmmmmmmk',
      'kmmmwwwwwwmmmmmk',
      'kmmmmwwwwmmmmmmk',
      '.kkmmmmmmmmmmkk.',
      '..kkmkkmmkkmkk..',
      '...kk.kmmk.kk...',
      '...k..kchk..k...',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '.....kgggk......',
      '.....kkkkk......',
    ],
  };

  S.item_staff = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      y: '#3fc8b0',
      l: '#eafff8',
      g: '#f6c94a',
      c: '#b07a44',
      h: '#7a4e28',
    },
    px: [
      '......kkkk......',
      '....kkyyyykk....',
      '...kyyllllyyk...',
      '...kyllllllyk...',
      '...kyyllllyyk...',
      '....kkyyyykk....',
      '......kkkk......',
      '......kggk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kkkk......',
    ],
  };

  S.item_wand = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      y: '#a06ce0',
      l: '#e2d8ff',
      w: '#ffffff',
      g: '#f6c94a',
      c: '#b07a44',
      h: '#7a4e28',
    },
    px: [
      '.......kk.......',
      '......kyyk......',
      '.....kyllyk..w..',
      '.....kyllyk.www.',
      '.....kyllyk..w..',
      '......kyyk......',
      '......kkkk......',
      '......kggk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kchk......',
      '......kkkk......',
    ],
  };

  S.item_bow = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      c: '#b07a44',
      h: '#7a4e28',
      s: '#f2ece0',
      g: '#4a3018',
    },
    px: [
      '......kck..k....',
      '.....kchk..s....',
      '....kchk...s....',
      '...kchk....s....',
      '..kchk.....s....',
      '..kchk.....s....',
      '.kchk......s....',
      '.kggk......s....',
      '.kggk......s....',
      '.kchk......s....',
      '..kchk.....s....',
      '..kchk.....s....',
      '...kchk....s....',
      '....kchk...s....',
      '.....kchk..s....',
      '......kck..k....',
    ],
  };

  S.item_whip = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      l: '#e0a868',
      c: '#a8642a',
      h: '#6b4a2f',
      g: '#f6c94a',
    },
    px: [
      '...........klck.',
      '..........klck..',
      '.........klck...',
      '.......klck.....',
      '......klck......',
      '......klck......',
      '.......klck.....',
      '........klck....',
      '........klck....',
      '.......klck.....',
      '......klck......',
      '....kggggk......',
      '....khhhhk......',
      '....khhhhk......',
      '....kggggk......',
      '....kkkkkk......',
    ],
  };

  S.item_claws = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#eef4f8',
      s: '#a9b4c2',
      m: '#7a4e28',
      h: '#3a2a1a',
    },
    px: [
      '................',
      '.......kk.......',
      '......kwsk......',
      '..kk..kwsk..kk..',
      '.kwsk.kwsk.kwsk.',
      '.kwsk.kwsk.kwsk.',
      '.kwsk.kwsk.kwsk.',
      '.kwsk.kwsk.kwsk.',
      '.kwsk.kwsk.kwsk.',
      '.kwsk.kwsk.kwsk.',
      '.kkkkkkkkkkkkkk.',
      '.kmmmmmmmmmmmmk.',
      '.kmhhmmhhmmhhmk.',
      '.kmmmmmmmmmmmmk.',
      '.kkkkkkkkkkkkkk.',
      '................',
    ],
  };

  // ----------------------------------------------------------------- armors

  S.item_leather_armor = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      c: '#a06a3a',
      d: '#6b4425',
      b: '#4a3018',
      g: '#f6c94a',
    },
    px: [
      '................',
      '...kkkk..kkkk...',
      '..kdddk..kdddk..',
      '..kdccdkkdccdk..',
      '.kddccccccccddk.',
      '.kdccccccccccdk.',
      '.kdccccccccccdk.',
      '.kdccccccccccdk.',
      '.kkkkkkkkkkkkkk.',
      '.kbbbbbggbbbbbk.',
      '.kkkkkkkkkkkkkk.',
      '..kdccccccccdk..',
      '..kdccccccccdk..',
      '..kdccccccccdk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  };

  S.item_chain_armor = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      m: '#8a96a4',
      d: '#57606e',
      b: '#4a3018',
      g: '#f6c94a',
    },
    px: [
      '................',
      '...kkkk..kkkk...',
      '..kmdmk..kmdmk..',
      '..kdmdmkkmdmdk..',
      '.kmdmdmdmdmdmk..',
      '.kdmdmdmdmdmdk..',
      '.kmdmdmdmdmdmk..',
      '.kdmdmdmdmdmdk..',
      '.kkkkkkkkkkkkkk.',
      '.kbbbbbggbbbbbk.',
      '.kkkkkkkkkkkkkk.',
      '..kmdmdmdmdmdk..',
      '..kdmdmdmdmdmk..',
      '..kmdmdmdmdmdk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  };

  S.item_plate_armor = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#e6ecf2',
      m: '#9aa7b3',
      d: '#5c6878',
    },
    px: [
      '................',
      '.kkkk......kkkk.',
      'kwwwwk.kk.kwwwwk',
      'kwmmmkkwwkkmmmwk',
      'kmmmkwwwwwwkmmmk',
      '.kkkwwwwwwwwkkk.',
      '...kwwwwwwwwk...',
      '...kwwwmmwwwk...',
      '...kwmmmmmmwk...',
      '...kwwmmmmwwk...',
      '...kwwwmmwwwk...',
      '...kwwwwwwwwk...',
      '...kkkkkkkkkk...',
      '....kwwwwwwk....',
      '....kwmddmwk....',
      '....kkkkkkkk....',
    ],
  };

  S.item_robe = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      p: '#6a4aa8',
      q: '#42296e',
      l: '#9a7ad8',
      d: '#2a1030',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '....kppppppk....',
      '...kppkkkkppk...',
      '...kpkddddkpk...',
      '...kpkddddkpk...',
      '...kppkkkkppk...',
      '..klpppppppppk..',
      '..klpqppppppqk..',
      '.klppqppppppqpk.',
      '.klppqppppppqpk.',
      '.klpqqppppppqqk.',
      'klppqppppppppqpk',
      'klpqppppppppppqk',
      'klppqppppppppqpk',
      'kkkkkkkkkkkkkkkk',
    ],
  };

  S.item_hide_armor = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      h: '#a8763e',
      f: '#d8b083',
      b: '#6b4425',
    },
    px: [
      '................',
      '...kkkk..kkkk...',
      '..kfffk..kfffk..',
      '..kfhhkkkkhhfk..',
      '.kfhhhhhhhhhhfk.',
      '.kfhbhhhhhhbhfk.',
      '.kfhhhhbbhhhhfk.',
      '.kfhhhhhhhhhhfk.',
      '.kfhbhhhhhhbhfk.',
      '.kfhhhhhhhhhhfk.',
      '.kfhhhbbhhhhhfk.',
      '..kfhhhhhhhhfk..',
      '..kfhhbhhbhhfk..',
      '..kfhhhhhhhhfk..',
      '..kffkkffkkffk..',
      '...kk..kk..kk...',
    ],
  };

  S.item_shell_armor = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      g: '#3f8a5a',
      d: '#25543a',
      l: '#7ac088',
      w: '#c8f0c0',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '...kkggggggkk...',
      '..kgggkkkkgggk..',
      '.kggkddddddkggk.',
      'kgggkdlldldkgggk',
      'kggkdlwldlldkggk',
      'kgkdlllddllldkgk',
      'kgkdllddddlldkgk',
      'kggkdllldlldkggk',
      'kgggkdlldldkgggk',
      '.kggkddddddkggk.',
      '..kgggkkkkgggk..',
      '...kkggggggkk...',
      '.....kkkkkk.....',
      '................',
    ],
  };

  // ------------------------------------------------------------ accessories

  S.item_ring = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      g: '#f6c94a',
      o: '#ad7a1c',
      p: '#c83a6a',
      l: '#ff8ab0',
    },
    px: [
      '................',
      '.......kk.......',
      '......kllk......',
      '.....kpllpk.....',
      '.....kpllpk.....',
      '....kkkppkkk....',
      '...kggkkkkggk...',
      '..kggk....kggk..',
      '..kgok....kogk..',
      '..kgok....kogk..',
      '..kgok....kogk..',
      '..kggk....kggk..',
      '...kggk..kggk...',
      '....kggkkggk....',
      '.....kggggk.....',
      '.....kkkkkk.....',
    ],
  };

  S.item_amulet = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      c: '#c8a24a',
      g: '#f6c94a',
      o: '#ad7a1c',
      p: '#2a8ac0',
      l: '#8ce0ff',
    },
    px: [
      '..kk........kk..',
      '..kck......kck..',
      '...kck....kck...',
      '....kck..kck....',
      '.....kckkck.....',
      '......kkkk......',
      '.....kggggk.....',
      '...kkggggggkk...',
      '..kgggppppgggk..',
      '..kggppllppggk..',
      '..kggppllppggk..',
      '..kgooppppoogk..',
      '...kkggggggkk...',
      '.....kggggk.....',
      '......kkkk......',
      '................',
    ],
  };

  S.item_charm = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      h: '#8a5a30',
      y: '#f6c94a',
      r: '#c83a4a',
      g: '#3f9a5a',
    },
    px: [
      '......khhk......',
      '......khhk......',
      '......khhk......',
      '......kyyk......',
      '.....kyyyyk.....',
      '....kyyrryyk....',
      'kkkkyyrrrryykkkk',
      'khhkyrrggrrykhhk',
      'khhkyrrggrrykhhk',
      'kkkkyyrrrryykkkk',
      '....kyyrryyk....',
      '.....kyyyyk.....',
      '......kyyk......',
      '......khhk......',
      '......khhk......',
      '......khhk......',
    ],
  };

  S.item_feather = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      l: '#b8f0e0',
      m: '#2f8a86',
      s: '#efe8d8',
    },
    px: [
      '................',
      '.........kkk....',
      '........klsk....',
      '.......kllsmk...',
      '......kllsmmk...',
      '......kllsmmk...',
      '.....kllsmmmk...',
      '.....kllsmmmk...',
      '....kllsmmmmk...',
      '....kllsmmmk....',
      '...kllsmmmk.....',
      '...klsmmk.......',
      '..klsmk.........',
      '..ksk...........',
      '.ksk............',
      '.kk.............',
    ],
  };

  S.item_tooth = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#f4f1e8',
      n: '#b8ae9a',
      d: '#3a2a30',
    },
    px: [
      '................',
      '...kkkkkkkkkk...',
      '..kwwwwwwwwwwk..',
      '..kwwwkddkwnnk..',
      '..kwwwkddkwnnk..',
      '...kwwwwwwwnnk..',
      '...kwwwwwwwnk...',
      '....kwwwwwwnk...',
      '....kwwwwwnnk...',
      '.....kwwwwnk....',
      '.....kwwwnnk....',
      '......kwwnk.....',
      '......kwwnk.....',
      '.......kwnk.....',
      '.......kwk......',
      '.......kk.......',
    ],
  };

  S.item_idol = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      s: '#5c6878',
      t: '#8e9aa8',
      u: '#c2ccd6',
      r: '#5ef2d0',
      g: '#f6c94a',
    },
    px: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kggggggggggk..',
      '..kkkkkkkkkkkk..',
      '...ksttttttsk...',
      '...kskkttkksk...',
      '...kskrttrksk...',
      '...kskkttkksk...',
      '...kstkuuktsk...',
      '...ksttuuttsk...',
      '..kkkkkkkkkkkk..',
      '..ksuuuuuuuusk..',
      '..kskukukukusk..',
      '..kkkkkkkkkkkk..',
      '.kssssssssssssk.',
      '.kkkkkkkkkkkkkk.',
    ],
  };

  S.item_boots = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      c: '#c8945a',
      b: '#7a4e28',
      d: '#3a2a1a',
      g: '#f6c94a',
    },
    px: [
      '................',
      '...kkkkkk.......',
      '...kcccck.......',
      '...kcccck.......',
      '...kkkkkk.......',
      '...kbbbbk.......',
      '...kbbbbk.......',
      '...kbgggk.......',
      '...kbbbbk.......',
      '...kbbbbk.......',
      '...kbbbbk.......',
      '...kbbbbbkk.....',
      '...kbbbbbbbbk...',
      '..kbbbbbbbbbbk..',
      '..kddddddddddk..',
      '..kkkkkkkkkkkk..',
    ],
  };

  S.item_cloak = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      p: '#3a6ea8',
      q: '#24466e',
      l: '#6fa8dc',
      g: '#f6c94a',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '....kpkggkpk....',
      '...kppkggkppk...',
      '..kpppkkkkpppk..',
      '..klpppppppppk..',
      '..klppppppppqk..',
      '.klpppppppppqpk.',
      '.klppppppppqppk.',
      '.klpqpppppppqpk.',
      'klppqpppppppqppk',
      'klpqqpppppppqqpk',
      'klpqpppppppppqpk',
      'klqppppppppppqpk',
      'kppkkppkkppkkppk',
      '.kk..kk..kk..kk.',
    ],
  };

  S.item_gem = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      w: '#dff6ff',
      l: '#7fd8f8',
      p: '#2a8ac0',
      d: '#175a86',
    },
    px: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kwwwwwwwwwwk..',
      '.kkkkkkkkkkkkkk.',
      'kwllkllllllkllwk',
      'kllpkppppppkpplk',
      '.klppkppppkppdk.',
      '..kppkppppkppk..',
      '...kpkppppkpk...',
      '...kpkppppkpk...',
      '....kdppppdk....',
      '.....kdppdk.....',
      '......kddk......',
      '.......kk.......',
      '................',
    ],
  };

  // ---------------------------------------------------------------- potions
  // Shared bottle silhouette: cork (u/v), glass (a), liquid (m light / l mid / d dark).

  const bottle = (l, m, d) => ({
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      u: '#c8945a',
      v: '#8a5a30',
      a: '#dfe8f0',
      m: m,
      l: l,
      d: d,
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '.....kuuuuk.....',
      '.....kuvvuk.....',
      '.....kkkkkk.....',
      '......kaak......',
      '.....kaaaak.....',
      '...kkaaaaaakk...',
      '..kammmmmmmmdk..',
      '..kamllllllldk..',
      '..kamllllllldk..',
      '..kalllllllldk..',
      '..kalllllllldk..',
      '..kadllllllddk..',
      '..kddddddddddk..',
      '..kkkkkkkkkkkk..',
    ],
  });

  S.potion_red = bottle('#d02a3a', '#ff7a7a', '#7a1020');
  S.potion_blue = bottle('#2a6ad0', '#7ab4ff', '#123a7a');
  S.potion_green = bottle('#2aa04a', '#84e894', '#0e5a28');
  S.potion_yellow = bottle('#e8c020', '#fff07a', '#8a6a08');
  S.potion_purple = bottle('#8a3ad0', '#c88aff', '#4a1080');
  S.potion_orange = bottle('#e87a10', '#ffbc5a', '#8a4200');

  S.potion_elixir = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      u: '#c8945a',
      a: '#dfe8f0',
      r: '#ff4a5a',
      o: '#ff9a2a',
      y: '#ffe040',
      g: '#4ae06a',
      b: '#3a9aff',
      p: '#b45aff',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '.y...kuuuuk...y.',
      '.....kuuuuk.....',
      '.....kkkkkk.....',
      '......kaak......',
      '.y...kaaaak...y.',
      '...kkaaaaaakk...',
      '..karrrrrrrrrk..',
      '..kaoooooooook..',
      '..kayyyyyyyyyk..',
      '..kagggggggggk..',
      '..kabbbbbbbbbk..',
      '..kapppppppppk..',
      '..kppppppppppk..',
      '..kkkkkkkkkkkk..',
    ],
  };

  S.potion_phoenix = {
    w: 16, h: 16,
    pal: {
      k: '#1b1023',
      u: '#c8945a',
      v: '#8a5a30',
      a: '#dfe8f0',
      y: '#ffe066',
      o: '#ff9a2a',
      r: '#e8502a',
      w: '#fff6c8',
      d: '#8a3a10',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '.....kuuuuk.....',
      '.....kuvvuk.....',
      '.....kkkkkk.....',
      '......kaak......',
      '.....kaaaak.....',
      '...kkaaooaakk...',
      '..kaaaoyyoaaak..',
      '..kaaroywyorak..',
      '..kaaroywyorak..',
      '..kaaroywyorak..',
      '..kaarooyoorak..',
      '..kaaadooodaak..',
      '..kdoooooooodk..',
      '..kkkkkkkkkkkk..',
    ],
  };

})();
