// js/sprites/ui_status.js — status effect icons, misc UI icons and jungle decorations.
// Text pixel grids; see docs/ART_SPEC.md. Plain script (not a module).
(function () {
  const S = (window.DJ = window.DJ || {}).SPRITES || (DJ.SPRITES = {});

  // ---------------------------------------------------------------- status --
  // 16x16, high-contrast silhouettes that must read above a health bar.

  S.status_poison = {
    w: 16, h: 16,
    pal: {
      k: '#0e2416',
      d: '#1f6b32',
      g: '#3fbf52',
      l: '#8cf06a',
      w: '#dcffb4',
    },
    px: [
      '................',
      '.......kk.......',
      '......kggk......',
      '.....kglggk.....',
      '....kgllgggk....',
      '....kgllgdgk....',
      '...kgllwgddgk...',
      '...kgllgggdgk...',
      '..kgglggggddgk..',
      '..kgglgggggddk..',
      '..kggggggggddk..',
      '...kgggggddgk...',
      '....kggdddgk....',
      '.....kgddgk.....',
      '......kkkk......',
      '................',
    ],
  };

  S.status_burn = {
    w: 16, h: 16,
    pal: {
      k: '#2a0c06',
      r: '#c22a10',
      o: '#f0791a',
      y: '#ffd24a',
      w: '#fff6c0',
    },
    px: [
      '................',
      '.......kk.......',
      '......krrk......',
      '......krok......',
      '.....kroork.....',
      '....kroyyork....',
      '....kroyyork....',
      '...kroyywyork...',
      '...kroywwyork...',
      '..kroyywwyyork..',
      '..kroyywwyyork..',
      '..krooywwyoork..',
      '..krrooyyoorrk..',
      '...krroyyorrk...',
      '....krroorrk....',
      '.....kkkkkk.....',
    ],
  };

  S.status_bleed = {
    w: 16, h: 16,
    pal: {
      k: '#2a0810',
      d: '#8a0f1e',
      g: '#d61f34',
      l: '#f2606e',
      w: '#ffd0d4',
    },
    px: [
      '................',
      '.......kk.......',
      '......kggk......',
      '.....kglggk.....',
      '....kgllgggk....',
      '....kgllgdgk....',
      '...kgllwgddgk...',
      '...kgllgggdgk...',
      '..kgglggggddgk..',
      '..kgglgggggddk..',
      '..kggggggggddk..',
      '...kgggggddgk...',
      '....kggdddgk....',
      '.....kgddgk.....',
      '......kkkk......',
      '................',
    ],
  };

  S.status_stun = {
    w: 16, h: 16,
    pal: {
      o: '#a8730a',
      y: '#ffd42a',
      w: '#fffbdc',
    },
    px: [
      '................',
      '............o...',
      '...........oyo..',
      '..........oyyyo.',
      '......o....oyo..',
      '......y.....o...',
      '.....yyy........',
      '.....yyy........',
      '..oyyywyyyo.....',
      '.....yyy........',
      '.....yyy........',
      '......y.........',
      '..o...o.........',
      '.oyo............',
      '..o.............',
      '................',
    ],
  };

  S.status_weak = {
    w: 16, h: 16,
    pal: {
      k: '#180a2a',
      p: '#7a3ac4',
      l: '#c79cf5',
      d: '#4a1e80',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '.....kpllpk.....',
      '.....kpllpk.....',
      '.....kpllpk.....',
      '.....kpllpk.....',
      '.....kpllpk.....',
      '.....kpllpk.....',
      '..kkkkpllpkkkk..',
      '..kppplldppppk..',
      '...kppplldppk...',
      '....kpplldpk....',
      '.....kplldk.....',
      '......kpdk......',
      '.......kk.......',
      '................',
    ],
  };

  S.status_guard = {
    w: 16, h: 16,
    pal: {
      k: '#0a1a2e',
      b: '#1f4f8c',
      l: '#5aa2e0',
      w: '#cfe8ff',
    },
    px: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kwwllllllllllk.',
      '.kwlllllllbbbbk.',
      '.kllllllllbbbbk.',
      '.kllllllllbbbbk.',
      '..kllllllbbbbk..',
      '..kllllllbbbbk..',
      '...kllllbbbbk...',
      '...kllllbbbbk...',
      '....klllbbbk....',
      '....klllbbbk....',
      '.....kllbbk.....',
      '......klbk......',
      '.......kk.......',
      '................',
    ],
  };

  S.status_haste = {
    w: 16, h: 16,
    pal: {
      k: '#3a1c02',
      o: '#f08a10',
      y: '#ffd867',
    },
    px: [
      '................',
      '................',
      '.kk.....kk......',
      '.kyk....kyk.....',
      '.kyok...kyok....',
      '.kyook..kyook...',
      '.kyoook.kyoook..',
      '.kyooookkyooook.',
      '.kyooookkyooook.',
      '.kyoook.kyoook..',
      '.kyook..kyook...',
      '.kyok...kyok....',
      '.kyk....kyk.....',
      '.kk.....kk......',
      '................',
      '................',
    ],
  };

  S.status_regen = {
    w: 16, h: 16,
    pal: {
      k: '#0b2a14',
      d: '#1c7a34',
      g: '#38c256',
      l: '#8ef07e',
    },
    px: [
      '................',
      '................',
      '.....kkkkkk.....',
      '.....kllgdk.....',
      '.....kllgdk.....',
      '..kkkkllgdkkkk..',
      '..kllllllgdddk..',
      '..kllgggggdddk..',
      '..kgggggggdddk..',
      '..kggggggddddk..',
      '..kkkkggddkkkk..',
      '.....kggddk.....',
      '.....kggddk.....',
      '.....kggddk.....',
      '.....kkkkkk.....',
      '................',
    ],
  };

  S.status_slow = {
    w: 16, h: 16,
    pal: {
      k: '#241407',
      b: '#8a5a24',
      w: '#cfe4ef',
      y: '#f2c04a',
    },
    px: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kbbbbbbbbbbk..',
      '...kwyyyyyywk...',
      '....kwyyyywk....',
      '.....kwyywk.....',
      '......kyyk......',
      '......kkkk......',
      '......kyyk......',
      '.....kwyywk.....',
      '....kwwyywwk....',
      '...kwyyyyyywk...',
      '..kwyyyyyyyywk..',
      '..kbbbbbbbbbbk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  };

  S.status_shield = {
    w: 16, h: 16,
    pal: {
      k: '#062026',
      c: '#1aa8bf',
      l: '#6ff0ff',
      w: '#e6ffff',
      d: '#12414d',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '...kkcccccckk...',
      '..kccwlllllcck..',
      '..kcwddddddlck..',
      '.kclddddddddlck.',
      '.kclddddddddlck.',
      '.kclddddddddlck.',
      '.kclddddddddlck.',
      '.kclddddddddlck.',
      '.kclddddddddlck.',
      '..kclddddddlck..',
      '..kccllllllcck..',
      '...kkcccccckk...',
      '.....kkkkkk.....',
      '................',
    ],
  };

  S.status_rage = {
    w: 16, h: 16,
    pal: {
      k: '#2a0409',
      r: '#d81f2e',
      l: '#ff8a7a',
      d: '#8a0c18',
    },
    px: [
      '................',
      '.......kk.......',
      '......krrk......',
      '.....krrrrk.....',
      '....krrllrrk....',
      '...krrrllrrrk...',
      '..krrrrllrrrrk..',
      '..kkkkrlldkkkk..',
      '.....krlldk.....',
      '.....krlldk.....',
      '.....krlldk.....',
      '.....krlldk.....',
      '.....krlldk.....',
      '.....krlldk.....',
      '.....kkkkkk.....',
      '................',
    ],
  };

  S.status_blind = {
    w: 16, h: 16,
    pal: {
      k: '#14161e',
      w: '#e8eef4',
      p: '#3a6ea8',
      d: '#0a0e14',
      r: '#e0323c',
    },
    px: [
      '................',
      '................',
      '.rr.............',
      '..rr............',
      '...rrkkkkkk.....',
      '...krrwwwwwkk...',
      '..kwwrrpppwwwk..',
      '.kwwwprrdppwwwk.',
      '.kwwwpprrppwwwk.',
      '..kwwwpprrwwwk..',
      '...kkwwwwrrkk...',
      '.....kkkkkrr....',
      '...........rr...',
      '............rr..',
      '................',
      '................',
    ],
  };

  // ------------------------------------------------------------------ misc --
  // 16x16 HUD icons: dark tinted outline + highlight so they pop on dark panels.

  S.icon_gold = {
    w: 16, h: 16,
    pal: {
      k: '#3a2408',
      o: '#a8721c',
      g: '#f0c040',
      y: '#fff2a0',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '...kkggggggkk...',
      '..kggyygggggok..',
      '..kgyyggggggok..',
      '.kgyyggoogggook.',
      '.kgygggoogggook.',
      '.kgggooooooggok.',
      '.kgggooooooggok.',
      '.kgggggoogggook.',
      '.kgggggooggoook.',
      '..kgggggggoook..',
      '..kgggggoooook..',
      '...kkooooookk...',
      '.....kkkkkk.....',
      '................',
    ],
  };

  S.icon_xp = {
    w: 16, h: 16,
    pal: {
      k: '#3a2a04',
      y: '#f2b81e',
      w: '#ffee88',
    },
    px: [
      '................',
      '.......kk.......',
      '......kwwk......',
      '......kwwk......',
      '.....kwwwwk.....',
      '.kkkkkwwwwkkkkk.',
      'kyyyyywwwwyyyyyk',
      '.kyyyywwwwyyyyk.',
      '..kyyywwwwyyyk..',
      '...kyywwwwyyk...',
      '..kyyywwwwyyyk..',
      '..kyyykkkkyyyk..',
      '.kyyyk....kyyyk.',
      'kyyyk......kyyyk',
      'kkk..........kkk',
      '................',
    ],
  };

  S.icon_hp = {
    w: 16, h: 16,
    pal: {
      k: '#2a0810',
      r: '#e03040',
      q: '#8a1020',
      w: '#ffb0b8',
    },
    px: [
      '................',
      '..kkkk....kkkk..',
      '.kwwrrrkkrrrrrk.',
      'kwwrrrrrrrrrrrqk',
      'kwrrrrrrrrrrrrqk',
      'krrrrrrrrrrrrrqk',
      '.krrrrrrrrrrrqk.',
      '..krrrrrrrrrqk..',
      '...krrrrrrrqk...',
      '....krrrrrqk....',
      '.....krrrqk.....',
      '......krqk......',
      '.......kk.......',
      '................',
      '................',
      '................',
    ],
  };

  S.icon_mp = {
    w: 16, h: 16,
    pal: {
      k: '#081a2e',
      d: '#12508a',
      g: '#2a8ad6',
      l: '#6fc8f5',
      w: '#d8f2ff',
    },
    px: [
      '................',
      '.......kk.......',
      '......kggk......',
      '.....kglggk.....',
      '....kgllgggk....',
      '....kgllgdgk....',
      '...kgllwgddgk...',
      '...kgllgggdgk...',
      '..kgglggggddgk..',
      '..kgglgggggddk..',
      '..kggggggggddk..',
      '...kgggggddgk...',
      '....kggdddgk....',
      '.....kgddgk.....',
      '......kkkk......',
      '................',
    ],
  };

  S.icon_gear = {
    w: 16, h: 16,
    pal: {
      k: '#1c2028',
      g: '#d8e2ec',
      m: '#8e9aa8',
      d: '#4a5462',
    },
    px: [
      '................',
      '....kkk..kkk....',
      '....kggkkgmk....',
      '....kggggmmk....',
      '.kkkggggmmmmkkk.',
      '.kggggkkkkmmmmk.',
      '.kgggk....kmmdk.',
      '..kggk....kmdk..',
      '..kgmk....kddk..',
      '.kgmmk....kdddk.',
      '.kmmmmkkkkddddk.',
      '.kkkmmmmddddkkk.',
      '....kmmddddk....',
      '....kmdkkddk....',
      '....kkk..kkk....',
      '................',
    ],
  };

  S.icon_book = {
    w: 16, h: 16,
    pal: {
      k: '#2a1a12',
      w: '#f4ecd8',
      n: '#a89878',
      b: '#8a4a24',
    },
    px: [
      '................',
      '................',
      '.......kk.......',
      '....kwwkkwwk....',
      '..kwwwwkkwwwwk..',
      '.kwwwwwkkwwwwwk.',
      'kwwwwwwkkwwwwwwk',
      'kwnnnwwkkwwnnnwk',
      'kwnnnnwkkwnnnnwk',
      'kwnnnwwkkwwnnnwk',
      'kwnnnnwkkwnnnnwk',
      'kwwwwwwkkwwwwwwk',
      'kbwwwwwkkwwwwwbk',
      'kbbbbbbkkbbbbbbk',
      '.kkkkkkkkkkkkkk.',
      '................',
    ],
  };

  S.icon_trophy = {
    w: 16, h: 16,
    pal: {
      k: '#3a2408',
      g: '#f0c040',
      y: '#fff2a0',
      o: '#a8721c',
    },
    px: [
      '................',
      '..kkkkkkkkkkkk..',
      '..kgyyggggggok..',
      '..kgggggggggok..',
      'kg.kgyggggook.gk',
      'kg.kgyggggook.gk',
      'kg.kggggggook.gk',
      'kkkkggggggookkkk',
      '....kggggggk....',
      '.....kggggk.....',
      '......kggk......',
      '......kggk......',
      '...kggggggggk...',
      '..kgggggggggok..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  };

  S.icon_skull = {
    w: 16, h: 16,
    pal: {
      k: '#241a20',
      w: '#eae4d8',
      d: '#12161c',
    },
    px: [
      '................',
      '....kkkkkkkk....',
      '..kkwwwwwwwwkk..',
      '.kwwwwwwwwwwwwk.',
      '.kwwwwwwwwwwwwk.',
      '.kwwkkkwwkkkwwk.',
      '.kwkdddwwdddkwk.',
      '.kwkdddwwdddkwk.',
      '.kwwkkkddkkkwwk.',
      '.kwwwwwddwwwwwk.',
      '..kwwwwkkwwwwk..',
      '..kwwwwkkwwwwk..',
      '...kwkwkkwkwk...',
      '...kwkwkkwkwk...',
      '....kkkkkkkk....',
      '................',
    ],
  };

  S.icon_map = {
    w: 16, h: 16,
    pal: {
      k: '#2a2016',
      p: '#e8d8ac',
      g: '#5a9a4a',
      r: '#d63a3a',
    },
    px: [
      '................',
      '................',
      '.kkkkkkkkkkkkkk.',
      '.kpppkppppkpppk.',
      '.kpppkppppkrprk.',
      '.kpggkpggpkprpk.',
      '.kpggkpgggkrprk.',
      '.kpppkpggpkpppk.',
      '.kprpkppppkpppk.',
      '.kpprkrpppkpppk.',
      '.kpppkprppkpgpk.',
      '.kpggkpprpkggpk.',
      '.kgggkpppgkgppk.',
      '.kkkkkkkkkkkkkk.',
      '................',
      '................',
    ],
  };

  S.icon_lock = {
    w: 16, h: 16,
    pal: {
      k: '#2a2010',
      m: '#b8b0a0',
      g: '#e8b830',
      y: '#fff0a8',
      o: '#9a6a10',
    },
    px: [
      '................',
      '.....kkkkkk.....',
      '....kkmmmmkk....',
      '....kmkkkkmk....',
      '....kmk..kmk....',
      '....kmk..kmk....',
      '..kkkmkkkkmkkk..',
      '..kgyyggggggok..',
      '..kgggkkkkggok..',
      '..kgggkkkkggok..',
      '..kggggkkgggok..',
      '..kggggkkgggok..',
      '..kgggggggggok..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
    ],
  };

  S.icon_check = {
    w: 16, h: 16,
    pal: {
      k: '#0a2a12',
      g: '#2ea84a',
      l: '#7ff086',
    },
    px: [
      '................',
      '................',
      '...........kkk..',
      '..........kkllk.',
      '.........kkllgk.',
      '........kkllggk.',
      '.kk.....kllggk..',
      'kllk...kllggk...',
      'kllgk.kllggk....',
      '.kllgkllggk.....',
      '..kllgllggk.....',
      '...kllgggk......',
      '....kllggk......',
      '.....kggk.......',
      '......kk........',
      '................',
    ],
  };

  S.icon_arrow_right = {
    w: 16, h: 16,
    pal: {
      k: '#1a2028',
      w: '#c8d4e0',
      l: '#f0f6ff',
      d: '#7a8899',
    },
    px: [
      '................',
      '................',
      '.........kk.....',
      '.........kwk....',
      '.........kwwk...',
      '.kkkkkkkkkwwk...',
      '.klllwwwwwwwwk..',
      '.kllwwwwwwwwwwk.',
      '.kwwwwwwwwwwwwk.',
      '.kwwwwwwwddddk..',
      '.kkkkkkkkkddk...',
      '.........kddk...',
      '.........kdk....',
      '.........kk.....',
      '................',
      '................',
    ],
  };

  // ----------------------------------------------------------- decorations --
  // Jungle scenery for dressing screen backgrounds: lush greens, warm torchlight.

  S.deco_leaf = {
    w: 16, h: 16,
    pal: {
      k: '#0d2a14',
      d: '#1e6b2c',
      g: '#38a544',
      l: '#6fd45c',
      s: '#4a6b28',
    },
    px: [
      '.......kk.......',
      '......kllk......',
      '.....kllkgk.....',
      '....klldkggk....',
      '...klldlkgggk...',
      '..klldllkggggk..',
      '..klllldkgggdk..',
      '.klllldlkggggdk.',
      '.kllldllkgggddk.',
      '..klldllkggddk..',
      '...klldlkgddk...',
      '....klldkgdk....',
      '.....kllkdk.....',
      '......klkk......',
      '.......ksk......',
      '.......ksk......',
    ],
  };

  S.deco_vine = {
    w: 16, h: 32,
    pal: {
      k: '#0d2a14',
      b: '#4a6b28',
      g: '#38a544',
      l: '#6fd45c',
    },
    px: [
      '......kbbk......',
      '......kbbk......',
      '......kbbk.kkk..',
      '......kbbkkllgk.',
      '......kbbklllggk',
      '......kbbkkllgk.',
      '......kbbk.kkk..',
      '.......kbbk.....',
      '.......kbbk.....',
      '...kkk.kbbk.....',
      '..kgllkkbbk.....',
      '.kgglllkbbk.....',
      '..kgllkkbbk.....',
      '...kkk.kbbk.....',
      '......kbbk......',
      '.....kbbk.......',
      '.....kbbk.kkk...',
      '.....kbbkkllgk..',
      '.....kbbklllggk.',
      '.....kbbkkllgk..',
      '.....kbbk.kkk...',
      '......kbbk......',
      '.......kbbk.....',
      '...kkk.kbbk.....',
      '..kgllkkbbk.....',
      '.kgglllkbbk.....',
      '..kgllkkbbk.....',
      '...kkk.kbbk.....',
      '.......kbbk.....',
      '.......kbbk.....',
      '.......kbbk.....',
      '.......kkkk.....',
    ],
  };

  S.deco_flower = {
    w: 16, h: 16,
    pal: {
      k: '#2a0a20',
      p: '#e8408a',
      w: '#ffb0d8',
      y: '#ffd84a',
      o: '#c07a10',
      g: '#3f8a3a',
    },
    px: [
      '................',
      '......kkkk......',
      '.....kpwwpk.....',
      '..kkkkpwwpkkkk..',
      '.kpwwpyyyypwwpk.',
      '.kpwppyooyppwpk.',
      '.kkpppyyyypppkk.',
      '..kkkppyyppkkk..',
      '....kppkkppk....',
      '......kgk.......',
      '......kgk.......',
      '...kkk.kgk......',
      '..kgggkkgk.kkk..',
      '..kgggkkgkkgggk.',
      '...kkk.kgk.kkk..',
      '.......kgk......',
    ],
  };

  S.deco_mushroom = {
    w: 16, h: 16,
    pal: {
      k: '#2a0e10',
      r: '#d43038',
      w: '#fff0e0',
      d: '#8a1a24',
      c: '#f0e0c0',
      n: '#c0a880',
    },
    px: [
      '................',
      '....kkkkkkkk....',
      '..kkrrrrwwrrkk..',
      '.krrwwrrrwwwrrk.',
      'krrwwwwrrrwwwrrk',
      'krrwwwwrrrrwwrrk',
      'krrrrrrwwrrrrrrk',
      'krrrrrrwwrrrrrrk',
      'kkddddddddddddkk',
      '....kkcccckk....',
      '.....kccnck.....',
      '.....kccnck.....',
      '.....kccnck.....',
      '....kcccnnck....',
      '...kcccnnnnck...',
      '...kkkkkkkkkk...',
    ],
  };

  S.deco_torch = {
    w: 16, h: 24,
    pal: {
      k: '#2a1408',
      r: '#c22a10',
      o: '#f0791a',
      y: '#ffd24a',
      w: '#fff6c0',
      b: '#6b4a2f',
      c: '#9c7048',
      n: '#4a2a12',
    },
    px: [
      '.......kk.......',
      '......kryk......',
      '.....kryyrk.....',
      '.....kryyrk.....',
      '....kroyyork....',
      '...kroyywyork...',
      '...kroywwyork...',
      '..kroyywwyyork..',
      '..kroyywwyyork..',
      '..krooywwyoork..',
      '..krrooyyoorrk..',
      '...krroyyorrk...',
      '....krroorrk....',
      '....kkkkkkkk....',
      '....knccccnk....',
      '....kncnncnk....',
      '....knccccnk....',
      '.....kknnkk.....',
      '......kbck......',
      '......kbck......',
      '......kbck......',
      '......kbck......',
      '......kbck......',
      '......kkkk......',
    ],
  };

  S.deco_rock = {
    w: 24, h: 16,
    pal: {
      k: '#181a20',
      s: '#4a505c',
      m: '#6e7684',
      l: '#98a2b0',
      g: '#3f8a3a',
      e: '#5fbf4a',
    },
    px: [
      '........................',
      '..........kkkk..........',
      '........kkeeggkk........',
      '......kkeeggeeggkk......',
      '....kkggeeggggllllkk....',
      '...kggeeggggllllllmk....',
      '..kegggegggllllmmmmmk...',
      '.kgglllllllllmmmmmmmk...',
      '.kellllllllmmmmmmmmmsk..',
      'kllllllmmmmmmmmmmmsssk..',
      'kllllmmmmmmmmmmmssssssk.',
      'kllmmmmmmmmmmmmssssssssk',
      'kmmmmmmmmmmmmssssssssssk',
      'kmmmmmmmmmmssssssssssssk',
      '.kssssssssssssssssssssk.',
      '..kkkkkkkkkkkkkkkkkkkk..',
    ],
  };

  S.deco_fern = {
    w: 24, h: 16,
    pal: {
      k: '#0d2a14',
      s: '#4a6b28',
      d: '#1e6b2c',
      g: '#38a544',
      l: '#6fd45c',
    },
    px: [
      '...........kk...........',
      '..........klsk..........',
      '..........klslk.........',
      '.kkk......klslk.....kkk.',
      '.kslk.....klslk....klsk.',
      '.ksllk...kllslk...kllsk.',
      'kgssggk..kggsgk..kggssgk',
      '.kgsgggk.kggsgk.kgggsgk.',
      '.kggsgggkgggsggkgggsggk.',
      '.kggssggggggsgggggssggk.',
      '..kggssgggggsggggssggk..',
      '..kdddssddddsdddssdddk..',
      '...kdddssdddsddssdddk...',
      '....kkddssddsdssddkk....',
      '......kddssdsssddk......',
      '.......kkkkkkkkkk.......',
    ],
  };

  S.deco_tree = {
    w: 32, h: 48,
    pal: {
      k: '#0d1a10',
      l: '#6fd45c',
      g: '#38a544',
      d: '#1e6b2c',
      b: '#6b4a2f',
      c: '#9c7048',
      n: '#4a3018',
    },
    px: [
      '........kkkkkk...kkkkkkk........',
      '.......kllllllkkkggggggk........',
      '.......kllllllggggggggggk.......',
      '.......kllllggggggggggggk.......',
      '.......kllggggggggggggggk.......',
      '.......kgggggggggggggggggkkk....',
      'kkkkkkkgggggggggggggggggggggkkk.',
      'klllggggggggggggggggggggggggdddk',
      'klggggggggggggggggggggggggdddddk',
      'kgggggggggggggggggggggggdddddddk',
      'kgggggggggggggggggggggdddddddddk',
      'kgggggggggggggggggggdddddddddddk',
      'kgggggggggggggggggdddddddddddddk',
      'kgggggggggggggggdddddddddddddddk',
      'kgggggggggggggdddddddddddddddddk',
      'kgggggggggggdddddddddddddddddddk',
      'kkkkggggggdddddddddddddddddkkkk.',
      '....kgggddddddddddddddddddk.....',
      '....kgddddddddddddddddddddk.....',
      '....kdddddddddddddddddddddk.....',
      '.....kddddddddddddddddddkk......',
      '......kkdddddddddddddddk........',
      '........kdddddddddkkkkk.........',
      '.........kkkkkbbbk..............',
      '.............kbbbk..............',
      '.............kbbbk..............',
      '.............kbbbk..............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbk.............',
      '.............kbbbbnk............',
      '.............kbbbbnk............',
      '.............kbbbbnk............',
      '.............kbbbbnk............',
      '............kcbbbbnk............',
      '............kcbbbbnk............',
      '............kcbbbbnk............',
      '...........kccbbbbnnkk..........',
      '..........kcccbbbbnnnnk.........',
      '.........kccccbbbbnnnnnk........',
      '........kcccccbbbbnnnnnnk.......',
      '......kkkkkkkkkkkkkkkkkkkk......',
    ],
  };

  S.deco_totem = {
    w: 16, h: 32,
    pal: {
      k: '#1a0e06',
      b: '#5a3a1c',
      c: '#8a5a30',
      d: '#c08a50',
      e: '#2a1408',
      r: '#c8402a',
      t: '#3f8a3a',
    },
    px: [
      '..kkkkkkkkkkkk..',
      '..kdddddddddck..',
      '..kkkkkkkkkkkk..',
      '.kcddddddddddck.',
      '.kcdkeekdkeekck.',
      '.kcdkeekdkeekck.',
      '.kcdddkddkdddck.',
      '.kcdddkeekdddck.',
      '.kcdkkkkkkkkdck.',
      '.kcdkeeeeeekdck.',
      '.kcddkkkkkkddck.',
      '..kkkkkkkkkkkk..',
      '.kcrrrrrrrrrrck.',
      '..kkkkkkkkkkkk..',
      '.kcddddddddddck.',
      '.kcdkeekdkeekck.',
      '.kcdkeekdkeekck.',
      '.kcdddkddkdddck.',
      '.kcdddkeekdddck.',
      '.kcdkkkkkkkkdck.',
      '.kcdkeeeeeekdck.',
      '.kcddkkkkkkddck.',
      '..kkkkkkkkkkkk..',
      '.kcttttttttttck.',
      '..kkkkkkkkkkkk..',
      '.kcddddddddddck.',
      '.kcdkeekdkeekck.',
      '.kcdddkddkdddck.',
      '.kcdkeeeeeekdck.',
      '.kcddkkkkkkddck.',
      'kbbbbbbbbbbbbbbk',
      'kkkkkkkkkkkkkkkk',
    ],
  };

})();
